using LLMGameCreator.Application.Generation.Procedural;
using LLMGameCreator.Application.Projects;
using LLMGameCreator.GamePackage;
using LLMGameCreator.Runtime.Abstractions;

namespace LLMGameCreator.Application.Play.GeneratedCampaign;

public sealed class GeneratedCampaignSessionService
{
    private readonly ICurrentGamePackageService _currentProject; private readonly GeneratedCampaignSessionTruthService _truths; private readonly IUnifiedGameRuntimeService _runtime; private readonly GeneratedGameplaySaveService _saves; private readonly GeneratedGameplaySaveMigrationService _migration; private readonly GeneratedCampaignActionPlanner _planner; private readonly GeneratedCampaignProjectionService _projection; private readonly GeneratedCampaignEventPresenter _events;
    private GeneratedCampaignSession? _session; private GeneratedCampaignSessionStatus _status; private List<string> _diagnostics = []; private List<string> _recentEvents = [];
    public GeneratedCampaignSessionService(ICurrentGamePackageService currentProject, GeneratedCampaignSessionTruthService truths, IUnifiedGameRuntimeService runtime, GeneratedGameplaySaveService saves, GeneratedGameplaySaveMigrationService migration, GeneratedCampaignActionPlanner planner, GeneratedCampaignProjectionService projection, GeneratedCampaignEventPresenter events)
    { _currentProject=currentProject;_truths=truths;_runtime=runtime;_saves=saves;_migration=migration;_planner=planner;_projection=projection;_events=events; }
    public GeneratedCampaignSnapshot Refresh() { var captured=_truths.Capture(); if(_session is not null && (captured.Truth is null || !GeneratedCampaignSessionTruthService.Same(_session.Truth,captured.Truth))) { _status=GeneratedCampaignSessionStatus.STALE_PROJECT;_diagnostics=["campaign.project_truth_changed"]; } else if (_session is null) { _status=captured.Status;_diagnostics=captured.Diagnostics.ToList(); } return Snapshot(captured.Truth); }
    public GeneratedCampaignSnapshot StartNew() { var captured=_truths.Capture(); if(captured.Status!=GeneratedCampaignSessionStatus.READY || captured.Truth is null || _currentProject.CurrentPackage is null){_status=captured.Status;_diagnostics=captured.Diagnostics.ToList();return Snapshot(captured.Truth);} var result=_runtime.Start(_currentProject.CurrentPackage); if(!result.Success){_status=GeneratedCampaignSessionStatus.FAILED;_diagnostics=["campaign.runtime_command_failed"];_recentEvents=_events.Present(result).ToList();return Snapshot(captured.Truth);} _session=new GeneratedCampaignSession(captured.Truth,result.Session,"campaign"); _status=GeneratedCampaignSessionStatus.ACTIVE;_recentEvents=_events.Present(result).ToList();return Snapshot(captured.Truth); }
    public GeneratedCampaignSnapshot Execute(string actionId) { var captured=_truths.Capture(); if(_session is null){_status=GeneratedCampaignSessionStatus.READY;_diagnostics=["campaign.session_not_started"];return Snapshot(captured.Truth);} if(captured.Truth is null || !GeneratedCampaignSessionTruthService.Same(_session.Truth,captured.Truth)){_status=GeneratedCampaignSessionStatus.STALE_PROJECT;_diagnostics=["campaign.project_truth_changed"];return Snapshot(captured.Truth);} var planned=_planner.Plan(_currentProject.CurrentPackage!,_session.RuntimeSession).SingleOrDefault(x=>x.Action.ActionId==actionId); if(planned is null){_diagnostics=["campaign.action_unknown"];return Snapshot(captured.Truth);} if(!planned.Action.Enabled){_diagnostics=["campaign.action_disabled"];return Snapshot(captured.Truth);} var result=planned.PlayerCommand is not null ? _runtime.ExecutePlayerCommand(_currentProject.CurrentPackage!,_session.RuntimeSession,planned.PlayerCommand) : _runtime.ExecuteGameplayCommand(_currentProject.CurrentPackage!,_session.RuntimeSession,planned.RuntimeCommand!); _session=_session with { RuntimeSession=result.Session }; _recentEvents=_events.Present(result).ToList();_diagnostics=result.Success?[]:["campaign.runtime_command_failed"]; if(result.Success && planned.Action.Kind is GeneratedCampaignActionKind.BasicAttack or GeneratedCampaignActionKind.UseAbility or GeneratedCampaignActionKind.ResolveEncounter or GeneratedCampaignActionKind.CompleteQuest) { var refresh=_runtime.ExecuteGameplayCommand(_currentProject.CurrentPackage!,_session.RuntimeSession,new GameRuntimeCommand { Type=GameRuntimeCommandType.RefreshQuestObjectives }); _session=_session with { RuntimeSession=refresh.Session };_recentEvents.AddRange(_events.Present(refresh)); if(!refresh.Success)_diagnostics=["campaign.follow_up_failed"]; } return Snapshot(captured.Truth); }
    public GeneratedCampaignSnapshot Save(string slotName) { if(_session is null)return Refresh(); var result=_saves.Save(_session.Truth.ProjectFolder,slotName,_session.RuntimeSession);_diagnostics=result.Passed?[]:result.Diagnostics.ToList();_recentEvents=[result.Passed?"Сохранение создано":result.Diagnostics.FirstOrDefault()??"Ошибка сохранения"];_session=_session with { SlotName=slotName};return Snapshot(_session.Truth); }
    public GeneratedCampaignSnapshot Continue(string slotName) { var captured=_truths.Capture();if(captured.Truth is null)return Refresh();var result=_saves.Load(captured.Truth.ProjectFolder,slotName);if(!result.Passed || result.Session is null){_status=result.Status is GeneratedGameplaySaveStatus.PACKAGE_REBASE_REQUIRED or GeneratedGameplaySaveStatus.WORLD_MIGRATION_REQUIRED?GeneratedCampaignSessionStatus.SAVE_MIGRATION_REQUIRED:GeneratedCampaignSessionStatus.FAILED;_diagnostics=result.Diagnostics.ToList();return Snapshot(captured.Truth);} _session=new GeneratedCampaignSession(captured.Truth,result.Session,slotName);_status=GeneratedCampaignSessionStatus.ACTIVE;_diagnostics=[];return Snapshot(captured.Truth); }
    public GeneratedGameplaySaveListResult ListSaves()=>string.IsNullOrWhiteSpace(_currentProject.CurrentFolder)?new GeneratedGameplaySaveListResult():_saves.List(_currentProject.CurrentFolder);
    public GeneratedGameplaySaveMigrationPreview PreviewMigration(string slot)=>string.IsNullOrWhiteSpace(_currentProject.CurrentFolder)?new GeneratedGameplaySaveMigrationPreview():_migration.Preview(_currentProject.CurrentFolder,slot);
    public GeneratedCampaignSnapshot MigrateAndContinue(GeneratedGameplaySaveMigrationPreview preview) { var result=_migration.Apply(new GeneratedGameplaySaveMigrationApplyRequest { ProjectFolder=_currentProject.CurrentFolder??string.Empty,SlotName=preview.SlotName,SourceRevisionSha256=preview.SourceRevisionSha256,CandidateSessionSha256=preview.CandidateSessionSha256});if(!result.Passed || result.Session is null){_status=GeneratedCampaignSessionStatus.FAILED;_diagnostics=result.Diagnostics.ToList();return Refresh();}var captured=_truths.Capture();_session=new GeneratedCampaignSession(captured.Truth!,result.Session,preview.SlotName);_status=GeneratedCampaignSessionStatus.ACTIVE;return Snapshot(captured.Truth); }
    private GeneratedCampaignSnapshot Snapshot(GeneratedCampaignProjectTruth? truth) { var package=_currentProject.CurrentPackage; var actions=_session is not null && package is not null && _status==GeneratedCampaignSessionStatus.ACTIVE?_planner.Plan(package,_session.RuntimeSession).Select(x=>x.Action).ToList():[];return _projection.Project(_status,truth,package,_session?.RuntimeSession,actions,_recentEvents,_session?.SlotName??"campaign",_diagnostics); }
}
