<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LLMGameCreator.Domain\LLMGameCreator.Domain.csproj" />
    <ProjectReference Include="..\..\src\LLMGameCreator.GamePackage\LLMGameCreator.GamePackage.csproj" />
    <ProjectReference Include="..\..\src\LLMGameCreator.Runtime.Abstractions\LLMGameCreator.Runtime.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\LLMGameCreator.Runtime\LLMGameCreator.Runtime.csproj" />
    <ProjectReference Include="..\..\src\LLMGameCreator.Application\LLMGameCreator.Application.csproj" />
    <ProjectReference Include="..\..\src\LLMGameCreator.Infrastructure\LLMGameCreator.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>
