<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LLMGameCreator.Domain\LLMGameCreator.Domain.csproj" />
    <ProjectReference Include="..\LLMGameCreator.GamePackage\LLMGameCreator.GamePackage.csproj" />
    <ProjectReference Include="..\LLMGameCreator.Runtime.Abstractions\LLMGameCreator.Runtime.Abstractions.csproj" />
  </ItemGroup>
</Project>
