namespace LLMGameCreator.Application.Design.VisualWorldStreamPreviewWorkspace;

public sealed partial class VisualWorldStreamPreviewWorkspaceService
{
    private static string RenderWorkspaceReport(
        VisualWorldStreamPreviewWorkspaceReport report,
        VisualWorldStreamPreviewCatalog catalog,
        VisualWorldStreamPreviewProofStatusDocument proofStatus,
        VisualWorldPreviewWinFormsBindingInventory binding,
        VisualWorldPreviewWorkspaceQualityGate qualityGate,
        string deterministicReportHash)
    {
        var lines = new List<string>
        {
            "# Goal 096 Unity Handoff Inspector Probe Readiness Report",
            string.Empty,
            $"- implementationStatus: {report.ImplementationStatus}",
            $"- accepted: {report.Accepted.ToString().ToLowerInvariant()}",
            $"- manualGate: {report.ManualGate} required",
            $"- deterministicReportHash: {deterministicReportHash}",
            string.Empty,
            "## Summary",
            string.Empty,
            "Goal 096 extends the existing BCL-only Visual World Stream Preview Workspace so editor review can inspect Goal 095 Unity StreamingAssets handoff readiness without launching Unity. It loads real Goal 095 evidence and mirrored payload files by repository-relative path, compares hashes against the Goal 095 ledgers, and does not change Runtime, Unity behavior, providers, schema, project files, dependencies, binary media or raster media.",
            string.Empty,
            "## Catalog",
            string.Empty,
            $"- groupCount: {catalog.GroupCount}",
            $"- entryCount: {catalog.EntryCount}",
            $"- svgTextPreviewCount: {catalog.SvgTextPreviewCount}",
            $"- goal091StreamWindowEntryCount: {qualityGate.Goal091StreamWindowEntryCount}",
            string.Empty
        };
        lines.AddRange(catalog.Groups.Select(group =>
            "- " + group.GroupId + ": entries=" + group.EntryCount
            + ", svgEntries=" + group.SvgEntryCount
            + ", sourceGoal=" + group.SourceGoalId
            + ", status=" + group.Status));
        lines.AddRange(
        [
            string.Empty,
            "## Cache Export Inspector",
            string.Empty,
            $"- cacheExportPackageCount: {report.CacheExportPackageCount}",
            $"- cacheExportRecordCount: {report.CacheExportRecordCount}",
            $"- cacheExportSourceChunkCount: {report.CacheExportSourceChunkCount}",
            $"- cacheExportStreamWindowCount: {report.CacheExportStreamWindowCount}",
            $"- runtimeHandoffSidecarVisible: {report.RuntimeHandoffSidecarVisible.ToString().ToLowerInvariant()}",
            $"- runtimeHandoffSidecarMetadataOnly: {report.RuntimeHandoffSidecarMetadataOnly.ToString().ToLowerInvariant()}",
            $"- cacheReadbackProofPassed: {report.CacheReadbackProofPassed.ToString().ToLowerInvariant()}",
            $"- cacheOverlapReuseProofPassed: {report.CacheOverlapReuseProofPassed.ToString().ToLowerInvariant()}",
            $"- cacheNegativeProofPassed: {report.CacheNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- cacheInvalidationMatrixPassed: {report.CacheInvalidationMatrixPassed.ToString().ToLowerInvariant()}",
            $"- cacheNoRawFullWorldDump: {report.CacheNoRawFullWorldDump.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Unity Handoff Inspector",
            string.Empty,
            $"- unityPayloadFileCount: {report.UnityPayloadFileCount}",
            $"- unityPackageCount: {report.UnityPackageCount}",
            $"- unityExportRecordCount: {report.UnityExportRecordCount}",
            $"- unityStreamWindowCount: {report.UnityStreamWindowCount}",
            $"- unityUniqueChunkKeyCount: {report.UnityUniqueChunkKeyCount}",
            $"- unityProbeSourceInventoryVisible: {report.UnityProbeSourceInventoryVisible.ToString().ToLowerInvariant()}",
            $"- unityProbeSourceInventoryPassed: {report.UnityProbeSourceInventoryPassed.ToString().ToLowerInvariant()}",
            $"- unitySimulatedReadProofPassed: {report.UnitySimulatedReadProofPassed.ToString().ToLowerInvariant()}",
            $"- unityNegativeProofPassed: {report.UnityNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- unityAlphaRuntimeBootstrapUnchanged: {report.UnityAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- unityForbiddenAreasUnchanged: {report.UnityForbiddenAreasUnchanged.ToString().ToLowerInvariant()}",
            $"- unityHandoffMetadataOnly: {report.UnityHandoffMetadataOnly.ToString().ToLowerInvariant()}",
            $"- unityPayloadHashesMatchGoal095Ledger: {report.UnityPayloadHashesMatchGoal095Ledger.ToString().ToLowerInvariant()}",
            $"- goal095FilesDiscoveredByRelativePaths: {report.Goal095FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- noUnityFilesChangedByGoal096: {report.NoUnityFilesChangedByGoal096.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Geoworld Inspector",
            string.Empty,
            $"- geoworldOfflineBundleId: {report.GeoworldOfflineBundleId}",
            $"- geoworldNormalizedFeatureCount: {report.GeoworldNormalizedFeatureCount}",
            $"- geoworldWorldSourceGraphChunkCount: {report.GeoworldWorldSourceGraphChunkCount}",
            $"- geoworldStreamWindowChunkCount: {report.GeoworldStreamWindowChunkCount}",
            $"- geoworldBoundaryPrefetchPassed: {report.GeoworldBoundaryPrefetchPassed.ToString().ToLowerInvariant()}",
            $"- geoworldNegativeProofPassed: {report.GeoworldNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- geoworldQualityGatePassed: {report.GeoworldQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal099FilesDiscoveredByRelativePaths: {report.Goal099FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Handoff",
            string.Empty,
            $"- offlineGeoworldHandoffPackageCount: {report.OfflineGeoworldHandoffPackageCount}",
            $"- offlineGeoworldHandoffFeatureCount: {report.OfflineGeoworldHandoffFeatureCount}",
            $"- offlineGeoworldHandoffVisualCacheRecordCount: {report.OfflineGeoworldHandoffVisualCacheRecordCount}",
            $"- offlineGeoworldHandoffSourceChunkCount: {report.OfflineGeoworldHandoffSourceChunkCount}",
            $"- offlineGeoworldHandoffStreamWindowChunkCount: {report.OfflineGeoworldHandoffStreamWindowChunkCount}",
            $"- offlineGeoworldHandoffUnityPayloadFileCount: {report.OfflineGeoworldHandoffUnityPayloadFileCount}",
            $"- offlineGeoworldHandoffFeatureKindCounts: {report.OfflineGeoworldHandoffFeatureKindCountsSummary}",
            $"- offlineGeoworldHandoffSimulatedReadProofPassed: {report.OfflineGeoworldHandoffSimulatedReadProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffNegativeProofPassed: {report.OfflineGeoworldHandoffNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldHandoffAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffQualityGatePassed: {report.OfflineGeoworldHandoffQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal100FilesDiscoveredByRelativePaths: {report.Goal100FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Unity Preview",
            string.Empty,
            $"- offlineGeoworldUnityPreviewCommandCount: {report.OfflineGeoworldUnityPreviewCommandCount}",
            $"- offlineGeoworldUnityPreviewCommandKindCount: {report.OfflineGeoworldUnityPreviewCommandKindCount}",
            $"- offlineGeoworldUnityPreviewTravelWindowStepCount: {report.OfflineGeoworldUnityPreviewTravelWindowStepCount}",
            $"- offlineGeoworldUnityPreviewUnityPayloadFileCount: {report.OfflineGeoworldUnityPreviewUnityPayloadFileCount}",
            $"- offlineGeoworldUnityPreviewKindCoverage: {report.OfflineGeoworldUnityPreviewKindCoverageSummary}",
            $"- offlineGeoworldUnityPreviewUnityScriptsReady: {report.OfflineGeoworldUnityPreviewUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewSimulatedCommandProofPassed: {report.OfflineGeoworldUnityPreviewSimulatedCommandProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewNegativeProofPassed: {report.OfflineGeoworldUnityPreviewNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldUnityPreviewAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewQualityGatePassed: {report.OfflineGeoworldUnityPreviewQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal101FilesDiscoveredByRelativePaths: {report.Goal101FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Unity Editor Preview",
            string.Empty,
            $"- offlineGeoworldUnityEditorPreviewCommandCount: {report.OfflineGeoworldUnityEditorPreviewCommandCount}",
            $"- offlineGeoworldUnityEditorPreviewCommandKindCount: {report.OfflineGeoworldUnityEditorPreviewCommandKindCount}",
            $"- offlineGeoworldUnityEditorPreviewTravelWindowStepCount: {report.OfflineGeoworldUnityEditorPreviewTravelWindowStepCount}",
            $"- offlineGeoworldUnityEditorPreviewExpectedObjectCount: {report.OfflineGeoworldUnityEditorPreviewExpectedObjectCount}",
            $"- offlineGeoworldUnityEditorPreviewEditorWindowScriptPath: {report.OfflineGeoworldUnityEditorPreviewEditorWindowScriptPath}",
            $"- offlineGeoworldUnityEditorPreviewMenuItemMarker: {report.OfflineGeoworldUnityEditorPreviewMenuItemMarker}",
            $"- offlineGeoworldUnityEditorPreviewPayloadPath: {report.OfflineGeoworldUnityEditorPreviewPayloadPath}",
            $"- offlineGeoworldUnityEditorPreviewToolInventoryPassed: {report.OfflineGeoworldUnityEditorPreviewToolInventoryPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewEditorWindowScriptReady: {report.OfflineGeoworldUnityEditorPreviewEditorWindowScriptReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewSimulatedActionProofPassed: {report.OfflineGeoworldUnityEditorPreviewSimulatedActionProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewClearOperationProofPassed: {report.OfflineGeoworldUnityEditorPreviewClearOperationProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewNegativeProofPassed: {report.OfflineGeoworldUnityEditorPreviewNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldUnityEditorPreviewAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewQualityGatePassed: {report.OfflineGeoworldUnityEditorPreviewQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewManualInstructions: {report.OfflineGeoworldUnityEditorPreviewManualInstructions}",
            $"- goal102FilesDiscoveredByRelativePaths: {report.Goal102FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Play Mode Travel",
            string.Empty,
            $"- offlineGeoworldPlayModeTravelStepCount: {report.OfflineGeoworldPlayModeTravelStepCount}",
            $"- offlineGeoworldPlayModeTravelObjectCount: {report.OfflineGeoworldPlayModeTravelObjectCount}",
            $"- offlineGeoworldPlayModeTravelActiveChunkCounts: {report.OfflineGeoworldPlayModeTravelActiveChunkCounts}",
            $"- offlineGeoworldPlayModeTravelBoundaryPrefetchCounts: {report.OfflineGeoworldPlayModeTravelBoundaryPrefetchCounts}",
            $"- offlineGeoworldPlayModeTravelExpectedVisibleObjectCounts: {report.OfflineGeoworldPlayModeTravelExpectedVisibleObjectCounts}",
            $"- offlineGeoworldPlayModeTravelUnityScriptsReady: {report.OfflineGeoworldPlayModeTravelUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelEditorWindowReady: {report.OfflineGeoworldPlayModeTravelEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelSimulatedExecutionProofPassed: {report.OfflineGeoworldPlayModeTravelSimulatedExecutionProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelNegativeProofPassed: {report.OfflineGeoworldPlayModeTravelNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelGoal102BClosureRecorded: {report.OfflineGeoworldPlayModeTravelGoal102BClosureRecorded.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldPlayModeTravelAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelQualityGatePassed: {report.OfflineGeoworldPlayModeTravelQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal103FilesDiscoveredByRelativePaths: {report.Goal103FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Interactive Travel",
            string.Empty,
            $"- offlineGeoworldInteractiveTravelMovementSampleCount: {report.OfflineGeoworldInteractiveTravelMovementSampleCount}",
            $"- offlineGeoworldInteractiveTravelBoundaryCrossingCount: {report.OfflineGeoworldInteractiveTravelBoundaryCrossingCount}",
            $"- offlineGeoworldInteractiveTravelObjectCount: {report.OfflineGeoworldInteractiveTravelObjectCount}",
            $"- offlineGeoworldInteractiveTravelActiveChunkCounts: {report.OfflineGeoworldInteractiveTravelActiveChunkCounts}",
            $"- offlineGeoworldInteractiveTravelBoundaryPrefetchCounts: {report.OfflineGeoworldInteractiveTravelBoundaryPrefetchCounts}",
            $"- offlineGeoworldInteractiveTravelExpectedVisibleObjectCounts: {report.OfflineGeoworldInteractiveTravelExpectedVisibleObjectCounts}",
            $"- offlineGeoworldInteractiveTravelUnityScriptsReady: {report.OfflineGeoworldInteractiveTravelUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelEditorWindowReady: {report.OfflineGeoworldInteractiveTravelEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelSimulatedExecutionProofPassed: {report.OfflineGeoworldInteractiveTravelSimulatedExecutionProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelNegativeProofPassed: {report.OfflineGeoworldInteractiveTravelNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldInteractiveTravelAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelQualityGatePassed: {report.OfflineGeoworldInteractiveTravelQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal104FilesDiscoveredByRelativePaths: {report.Goal104FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Interactions",
            string.Empty,
            $"- offlineGeoworldInteractionTargetCount: {report.OfflineGeoworldInteractionTargetCount}",
            $"- offlineGeoworldInteractionActionKindCount: {report.OfflineGeoworldInteractionActionKindCount}",
            $"- offlineGeoworldInteractionActionCount: {report.OfflineGeoworldInteractionActionCount}",
            $"- offlineGeoworldInteractionScriptedEventCount: {report.OfflineGeoworldInteractionScriptedEventCount}",
            $"- offlineGeoworldInteractionStateDeltaCount: {report.OfflineGeoworldInteractionStateDeltaCount}",
            $"- offlineGeoworldInteractionFinalStateHash: {report.OfflineGeoworldInteractionFinalStateHash}",
            $"- offlineGeoworldInteractionStateHashChainPassed: {report.OfflineGeoworldInteractionStateHashChainPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionUnityScriptsReady: {report.OfflineGeoworldInteractionUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionEditorWindowReady: {report.OfflineGeoworldInteractionEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionUnitySafetyScanPassed: {report.OfflineGeoworldInteractionUnitySafetyScanPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionSimulatedSessionProofPassed: {report.OfflineGeoworldInteractionSimulatedSessionProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionNegativeProofPassed: {report.OfflineGeoworldInteractionNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldInteractionAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionQualityGatePassed: {report.OfflineGeoworldInteractionQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal105FilesDiscoveredByRelativePaths: {report.Goal105FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Session Replay",
            string.Empty,
            $"- offlineGeoworldSessionReplayStepCount: {report.OfflineGeoworldSessionReplayStepCount}",
            $"- offlineGeoworldSessionStateDeltaCount: {report.OfflineGeoworldSessionStateDeltaCount}",
            $"- offlineGeoworldSessionCheckpointStepIndex: {report.OfflineGeoworldSessionCheckpointStepIndex}",
            $"- offlineGeoworldSessionAcceptanceChecklistStepCount: {report.OfflineGeoworldSessionAcceptanceChecklistStepCount}",
            $"- offlineGeoworldSessionFinalStateHash: {report.OfflineGeoworldSessionFinalStateHash}",
            $"- offlineGeoworldSessionUnityScriptsReady: {report.OfflineGeoworldSessionUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionEditorWindowReady: {report.OfflineGeoworldSessionEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionSimulatedReplayProofPassed: {report.OfflineGeoworldSessionSimulatedReplayProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionNegativeProofPassed: {report.OfflineGeoworldSessionNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldSessionAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionQualityGatePassed: {report.OfflineGeoworldSessionQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal106FilesDiscoveredByRelativePaths: {report.Goal106FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Objective Acceptance",
            string.Empty,
            $"- offlineGeoworldObjectiveCount: {report.OfflineGeoworldObjectiveCount}",
            $"- offlineGeoworldObjectiveCompletedCount: {report.OfflineGeoworldObjectiveCompletedCount}",
            $"- offlineGeoworldObjectivePayloadFileCount: {report.OfflineGeoworldObjectivePayloadFileCount}",
            $"- offlineGeoworldObjectiveReplayStepCount: {report.OfflineGeoworldObjectiveReplayStepCount}",
            $"- offlineGeoworldObjectiveStateDeltaCount: {report.OfflineGeoworldObjectiveStateDeltaCount}",
            $"- offlineGeoworldObjectiveCheckpointStepIndex: {report.OfflineGeoworldObjectiveCheckpointStepIndex}",
            $"- offlineGeoworldObjectiveFinalStatus: {report.OfflineGeoworldObjectiveFinalStatus}",
            $"- offlineGeoworldObjectiveFinalStateHash: {report.OfflineGeoworldObjectiveFinalStateHash}",
            $"- offlineGeoworldObjectiveUnityScriptsReady: {report.OfflineGeoworldObjectiveUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveEditorWindowReady: {report.OfflineGeoworldObjectiveEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveReplayAcceptanceProofPassed: {report.OfflineGeoworldObjectiveReplayAcceptanceProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveNegativeProofPassed: {report.OfflineGeoworldObjectiveNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveAlphaQualityConsolidationPassed: {report.OfflineGeoworldObjectiveAlphaQualityConsolidationPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldObjectiveAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveQualityGatePassed: {report.OfflineGeoworldObjectiveQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal107FilesDiscoveredByRelativePaths: {report.Goal107FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Alpha Slice",
            string.Empty,
            $"- offlineGeoworldAlphaSliceComponentCount: {report.OfflineGeoworldAlphaSliceComponentCount}",
            $"- offlineGeoworldAlphaSliceReadyComponentCount: {report.OfflineGeoworldAlphaSliceReadyComponentCount}",
            $"- offlineGeoworldAlphaSliceObjectiveCount: {report.OfflineGeoworldAlphaSliceObjectiveCount}",
            $"- offlineGeoworldAlphaSliceCompletedObjectiveCount: {report.OfflineGeoworldAlphaSliceCompletedObjectiveCount}",
            $"- offlineGeoworldAlphaSliceFinalStatus: {report.OfflineGeoworldAlphaSliceFinalStatus}",
            $"- offlineGeoworldAlphaSliceUnityToolReady: {report.OfflineGeoworldAlphaSliceUnityToolReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceAcceptanceRunbookReady: {report.OfflineGeoworldAlphaSliceAcceptanceRunbookReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceFinalProofPassed: {report.OfflineGeoworldAlphaSliceFinalProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceNegativeProofPassed: {report.OfflineGeoworldAlphaSliceNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldAlphaSliceAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceQualityGatePassed: {report.OfflineGeoworldAlphaSliceQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal108FilesDiscoveredByRelativePaths: {report.Goal108FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Alpha Export Package",
            string.Empty,
            $"- offlineGeoworldAlphaExportPackageFileCount: {report.OfflineGeoworldAlphaExportPackageFileCount}",
            $"- offlineGeoworldAlphaExportIndexedFileCount: {report.OfflineGeoworldAlphaExportIndexedFileCount}",
            $"- offlineGeoworldAlphaExportChecksumStatus: {report.OfflineGeoworldAlphaExportChecksumStatus}",
            $"- offlineGeoworldAlphaExportCleanImportProofPassed: {report.OfflineGeoworldAlphaExportCleanImportProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportNegativeProofPassed: {report.OfflineGeoworldAlphaExportNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportUnityVerifierReady: {report.OfflineGeoworldAlphaExportUnityVerifierReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportEditorWindowReady: {report.OfflineGeoworldAlphaExportEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportWorkspaceBindingPassed: {report.OfflineGeoworldAlphaExportWorkspaceBindingPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportSourceLineagePassed: {report.OfflineGeoworldAlphaExportSourceLineagePassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportRunbookSummary: {report.OfflineGeoworldAlphaExportRunbookSummary}",
            $"- offlineGeoworldAlphaExportAcceptanceGateStatus: {report.OfflineGeoworldAlphaExportAcceptanceGateStatus}",
            $"- offlineGeoworldAlphaExportAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldAlphaExportAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportQualityGatePassed: {report.OfflineGeoworldAlphaExportQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal109FilesDiscoveredByRelativePaths: {report.Goal109FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Alpha Manual Acceptance",
            string.Empty,
            $"- offlineGeoworldAlphaManualAcceptanceChecklistStepCount: {report.OfflineGeoworldAlphaManualAcceptanceChecklistStepCount}",
            $"- offlineGeoworldAlphaManualAcceptancePayloadFileCount: {report.OfflineGeoworldAlphaManualAcceptancePayloadFileCount}",
            $"- offlineGeoworldAlphaManualAcceptanceExportFileCount: {report.OfflineGeoworldAlphaManualAcceptanceExportFileCount}",
            $"- offlineGeoworldAlphaManualAcceptanceAutomatedGatePassed: {report.OfflineGeoworldAlphaManualAcceptanceAutomatedGatePassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceManualPending: {report.OfflineGeoworldAlphaManualAcceptanceManualPending.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceUnityRunnerReady: {report.OfflineGeoworldAlphaManualAcceptanceUnityRunnerReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceSimulatedProofPassed: {report.OfflineGeoworldAlphaManualAcceptanceSimulatedProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceNegativeProofPassed: {report.OfflineGeoworldAlphaManualAcceptanceNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceWorkspaceBindingPassed: {report.OfflineGeoworldAlphaManualAcceptanceWorkspaceBindingPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldAlphaManualAcceptanceAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceQualityGatePassed: {report.OfflineGeoworldAlphaManualAcceptanceQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceResultTemplatePath: {report.OfflineGeoworldAlphaManualAcceptanceResultTemplatePath}",
            $"- offlineGeoworldAlphaManualAcceptanceReleaseRiskLinks: {report.OfflineGeoworldAlphaManualAcceptanceReleaseRiskLinks}",
            $"- offlineGeoworldAlphaManualAcceptanceMilestoneGateLinks: {report.OfflineGeoworldAlphaManualAcceptanceMilestoneGateLinks}",
            $"- goal110FilesDiscoveredByRelativePaths: {report.Goal110FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeDecisionStatus: {report.OfflineGeoworldAlphaManualResultIntakeDecisionStatus}",
            $"- offlineGeoworldAlphaManualResultIntakeResultFilePresent: {report.OfflineGeoworldAlphaManualResultIntakeResultFilePresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeAcceptableCandidate: {report.OfflineGeoworldAlphaManualResultIntakeAcceptableCandidate.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeAcceptedByCodex: {report.OfflineGeoworldAlphaManualResultIntakeAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeHumanAcceptanceStillRequired: {report.OfflineGeoworldAlphaManualResultIntakeHumanAcceptanceStillRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeChecklistHashMatched: {report.OfflineGeoworldAlphaManualResultIntakeChecklistHashMatched.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakePassedStepCount: {report.OfflineGeoworldAlphaManualResultIntakePassedStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeFailedStepCount: {report.OfflineGeoworldAlphaManualResultIntakeFailedStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakePendingStepCount: {report.OfflineGeoworldAlphaManualResultIntakePendingStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeSkippedStepCount: {report.OfflineGeoworldAlphaManualResultIntakeSkippedStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeMissingStepCount: {report.OfflineGeoworldAlphaManualResultIntakeMissingStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeDuplicateStepCount: {report.OfflineGeoworldAlphaManualResultIntakeDuplicateStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeQualityGatePassed: {report.OfflineGeoworldAlphaManualResultIntakeQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal111FilesDiscoveredByRelativePaths: {report.Goal111FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorStatus: {report.OfflineGeoworldAlphaAcceptanceOperatorStatus}",
            $"- offlineGeoworldAlphaAcceptanceOperatorGoal111DecisionStatus: {report.OfflineGeoworldAlphaAcceptanceOperatorGoal111DecisionStatus}",
            $"- offlineGeoworldAlphaAcceptanceOperatorManualResultPresent: {report.OfflineGeoworldAlphaAcceptanceOperatorManualResultPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorManualResultAvailableForHumanReview: {report.OfflineGeoworldAlphaAcceptanceOperatorManualResultAvailableForHumanReview.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorAcceptedByCodex: {report.OfflineGeoworldAlphaAcceptanceOperatorAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorHumanAcceptanceStillRequired: {report.OfflineGeoworldAlphaAcceptanceOperatorHumanAcceptanceStillRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorChecklistStepCount: {report.OfflineGeoworldAlphaAcceptanceOperatorChecklistStepCount}",
            $"- offlineGeoworldAlphaAcceptanceOperatorChecklistHashPresent: {report.OfflineGeoworldAlphaAcceptanceOperatorChecklistHashPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorQualityGatePassed: {report.OfflineGeoworldAlphaAcceptanceOperatorQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal112FilesDiscoveredByRelativePaths: {report.Goal112FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchStatus: {report.OfflineGeoworldAlphaManualResultWorkbenchStatus}",
            $"- offlineGeoworldAlphaManualResultWorkbenchGoal111DecisionStatus: {report.OfflineGeoworldAlphaManualResultWorkbenchGoal111DecisionStatus}",
            $"- offlineGeoworldAlphaManualResultWorkbenchGoal112OperatorStatus: {report.OfflineGeoworldAlphaManualResultWorkbenchGoal112OperatorStatus}",
            $"- offlineGeoworldAlphaManualResultWorkbenchManualResultPresent: {report.OfflineGeoworldAlphaManualResultWorkbenchManualResultPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchAcceptedByCodex: {report.OfflineGeoworldAlphaManualResultWorkbenchAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchHumanAcceptanceStillRequired: {report.OfflineGeoworldAlphaManualResultWorkbenchHumanAcceptanceStillRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchDraftTemplateOnly: {report.OfflineGeoworldAlphaManualResultWorkbenchDraftTemplateOnly.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchChecklistStepCount: {report.OfflineGeoworldAlphaManualResultWorkbenchChecklistStepCount}",
            $"- offlineGeoworldAlphaManualResultWorkbenchChecklistHashPresent: {report.OfflineGeoworldAlphaManualResultWorkbenchChecklistHashPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchQualityGatePassed: {report.OfflineGeoworldAlphaManualResultWorkbenchQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal113FilesDiscoveredByRelativePaths: {report.Goal113FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationDecisionStatus: {report.OfflineGeoworldAlphaHumanResultRevalidationDecisionStatus}",
            $"- offlineGeoworldAlphaHumanResultRevalidationGoal111DecisionStatus: {report.OfflineGeoworldAlphaHumanResultRevalidationGoal111DecisionStatus}",
            $"- offlineGeoworldAlphaHumanResultRevalidationManualResultPresent: {report.OfflineGeoworldAlphaHumanResultRevalidationManualResultPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationManualResultJsonValid: {report.OfflineGeoworldAlphaHumanResultRevalidationManualResultJsonValid.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationAcceptableCandidate: {report.OfflineGeoworldAlphaHumanResultRevalidationAcceptableCandidate.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationRecommendedHumanDecision: {report.OfflineGeoworldAlphaHumanResultRevalidationRecommendedHumanDecision}",
            $"- offlineGeoworldAlphaHumanResultRevalidationAcceptedByCodex: {report.OfflineGeoworldAlphaHumanResultRevalidationAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationHumanAcceptanceStillRequired: {report.OfflineGeoworldAlphaHumanResultRevalidationHumanAcceptanceStillRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationManualGateRemainsHumanDecision: {report.OfflineGeoworldAlphaHumanResultRevalidationManualGateRemainsHumanDecision.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationRequiredStepCount: {report.OfflineGeoworldAlphaHumanResultRevalidationRequiredStepCount}",
            $"- offlineGeoworldAlphaHumanResultRevalidationPassedStepCount: {report.OfflineGeoworldAlphaHumanResultRevalidationPassedStepCount}",
            $"- offlineGeoworldAlphaHumanResultRevalidationManualInputNotCommitted: {report.OfflineGeoworldAlphaHumanResultRevalidationManualInputNotCommitted.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationQualityGatePassed: {report.OfflineGeoworldAlphaHumanResultRevalidationQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal115FilesDiscoveredByRelativePaths: {report.Goal115FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Alpha Manual Gate Acceptance Record",
            string.Empty,
            $"- offlineGeoworldAlphaManualGateAcceptanceManualGate: {report.OfflineGeoworldAlphaManualGateAcceptanceManualGate}",
            $"- offlineGeoworldAlphaManualGateAcceptanceManualGateStatus: {report.OfflineGeoworldAlphaManualGateAcceptanceManualGateStatus}",
            $"- offlineGeoworldAlphaManualGateAcceptanceHumanAccepted: {report.OfflineGeoworldAlphaManualGateAcceptanceHumanAccepted.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceHumanDecisionStatement: {report.OfflineGeoworldAlphaManualGateAcceptanceHumanDecisionStatement}",
            $"- offlineGeoworldAlphaManualGateAcceptanceSourceDecisionStatus: {report.OfflineGeoworldAlphaManualGateAcceptanceSourceDecisionStatus}",
            $"- offlineGeoworldAlphaManualGateAcceptanceManualResultSha256: {report.OfflineGeoworldAlphaManualGateAcceptanceManualResultSha256}",
            $"- offlineGeoworldAlphaManualGateAcceptanceAcceptedByCodex: {report.OfflineGeoworldAlphaManualGateAcceptanceAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceManualInputNotCommitted: {report.OfflineGeoworldAlphaManualGateAcceptanceManualInputNotCommitted.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceRawManualResultEmbeddedInArtifacts: {report.OfflineGeoworldAlphaManualGateAcceptanceRawManualResultEmbeddedInArtifacts.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceRecommendedNextDecision: {report.OfflineGeoworldAlphaManualGateAcceptanceRecommendedNextDecision}",
            $"- offlineGeoworldAlphaManualGateAcceptanceNotFinalReleaseOrRuntimeBuild: {report.OfflineGeoworldAlphaManualGateAcceptanceNotFinalReleaseOrRuntimeBuild.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceNoRuntimeProviderOrNetworkChanges: {report.OfflineGeoworldAlphaManualGateAcceptanceNoRuntimeProviderOrNetworkChanges.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceNoUnityFileChangesRequired: {report.OfflineGeoworldAlphaManualGateAcceptanceNoUnityFileChangesRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceRequiredStepCount: {report.OfflineGeoworldAlphaManualGateAcceptanceRequiredStepCount}",
            $"- offlineGeoworldAlphaManualGateAcceptancePassedStepCount: {report.OfflineGeoworldAlphaManualGateAcceptancePassedStepCount}",
            $"- offlineGeoworldAlphaManualGateAcceptanceQualityGatePassed: {report.OfflineGeoworldAlphaManualGateAcceptanceQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal116FilesDiscoveredByRelativePaths: {report.Goal116FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Alpha Post-Acceptance Continuation Selection",
            string.Empty,
            $"- offlineGeoworldAlphaPostAcceptanceManualGateStatus: {report.OfflineGeoworldAlphaPostAcceptanceManualGateStatus}",
            $"- offlineGeoworldAlphaPostAcceptanceHumanAccepted: {report.OfflineGeoworldAlphaPostAcceptanceHumanAccepted.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaPostAcceptanceManualResultSha256: {report.OfflineGeoworldAlphaPostAcceptanceManualResultSha256}",
            $"- offlineGeoworldAlphaPostAcceptanceRecommendedNextLane: {report.OfflineGeoworldAlphaPostAcceptanceRecommendedNextLane}",
            $"- offlineGeoworldAlphaPostAcceptanceRecommendedNextGoalId: {report.OfflineGeoworldAlphaPostAcceptanceRecommendedNextGoalId}",
            $"- offlineGeoworldAlphaPostAcceptanceReadyLaneCount: {report.OfflineGeoworldAlphaPostAcceptanceReadyLaneCount}",
            $"- offlineGeoworldAlphaPostAcceptanceCandidateLaneCount: {report.OfflineGeoworldAlphaPostAcceptanceCandidateLaneCount}",
            $"- offlineGeoworldAlphaPostAcceptanceBlockedLaneCount: {report.OfflineGeoworldAlphaPostAcceptanceBlockedLaneCount}",
            $"- offlineGeoworldAlphaPostAcceptanceDoNotStartAutomatically: {report.OfflineGeoworldAlphaPostAcceptanceDoNotStartAutomatically.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaPostAcceptanceQualityGatePassed: {report.OfflineGeoworldAlphaPostAcceptanceQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal117FilesDiscoveredByRelativePaths: {report.Goal117FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Accepted Alpha Baseline Review",
            string.Empty,
            $"- offlineGeoworldAcceptedAlphaBaselineId: {report.OfflineGeoworldAcceptedAlphaBaselineId}",
            $"- offlineGeoworldAcceptedAlphaBaselineHash: {report.OfflineGeoworldAcceptedAlphaBaselineHash}",
            $"- offlineGeoworldAcceptedAlphaBaselineReady: {report.OfflineGeoworldAcceptedAlphaBaselineReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAcceptedAlphaManualGateStatus: {report.OfflineGeoworldAcceptedAlphaManualGateStatus}",
            $"- offlineGeoworldAcceptedAlphaRecommendedNextDecision: {report.OfflineGeoworldAcceptedAlphaRecommendedNextDecision}",
            $"- offlineGeoworldAcceptedAlphaIncludedSourceGoalCount: {report.OfflineGeoworldAcceptedAlphaIncludedSourceGoalCount}",
            $"- offlineGeoworldAcceptedAlphaAcceptedEvidenceRootCount: {report.OfflineGeoworldAcceptedAlphaAcceptedEvidenceRootCount}",
            $"- offlineGeoworldAcceptedAlphaProducedOnlyRootCount: {report.OfflineGeoworldAcceptedAlphaProducedOnlyRootCount}",
            $"- offlineGeoworldAcceptedAlphaBlockedOrSupersededNoteCount: {report.OfflineGeoworldAcceptedAlphaBlockedOrSupersededNoteCount}",
            $"- offlineGeoworldAcceptedAlphaDoNotStartAutomatically: {report.OfflineGeoworldAcceptedAlphaDoNotStartAutomatically.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAcceptedAlphaQualityGatePassed: {report.OfflineGeoworldAcceptedAlphaQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal118FilesDiscoveredByRelativePaths: {report.Goal118FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Proof Status",
            string.Empty,
            $"- proofStatusPassed: {proofStatus.Passed.ToString().ToLowerInvariant()}",
            $"- proofCount: {proofStatus.ProofCount}"
        ]);
        lines.AddRange(proofStatus.Proofs.Select(proof =>
            "- " + proof.ProofId + ": passed=" + proof.Passed.ToString().ToLowerInvariant()
            + ", path=" + proof.RelativePath));
        lines.AddRange(
        [
            string.Empty,
            "## WinForms Binding",
            string.Empty,
            $"- bindingPassed: {binding.Passed.ToString().ToLowerInvariant()}",
            $"- pageControlExists: {binding.PageControlExists.ToString().ToLowerInvariant()}",
            $"- designerExists: {binding.DesignerExists.ToString().ToLowerInvariant()}",
            $"- compositionRootRegistersService: {binding.CompositionRootRegistersService.ToString().ToLowerInvariant()}",
            $"- compositionRootRegistersPage: {binding.CompositionRootRegistersPage.ToString().ToLowerInvariant()}",
            $"- editorRegistryIncludesPage: {binding.EditorRegistryIncludesPage.ToString().ToLowerInvariant()}",
            $"- pageActivationLoadsApplicationResult: {binding.PageActivationLoadsApplicationResult.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysGroupsEntriesProofs: {binding.PageBindDisplaysGroupsEntriesProofs.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysCacheExports: {binding.PageBindDisplaysCacheExports.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysUnityHandoff: {binding.PageBindDisplaysUnityHandoff.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysGeoworld: {binding.PageBindDisplaysGeoworld.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldHandoff: {binding.PageBindDisplaysOfflineGeoworldHandoff.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldUnityPreview: {binding.PageBindDisplaysOfflineGeoworldUnityPreview.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldUnityEditorPreview: {binding.PageBindDisplaysOfflineGeoworldUnityEditorPreview.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldPlayModeTravel: {binding.PageBindDisplaysOfflineGeoworldPlayModeTravel.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldInteractiveTravel: {binding.PageBindDisplaysOfflineGeoworldInteractiveTravel.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldInteractions: {binding.PageBindDisplaysOfflineGeoworldInteractions.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldSessionReplay: {binding.PageBindDisplaysOfflineGeoworldSessionReplay.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldObjectiveAcceptance: {binding.PageBindDisplaysOfflineGeoworldObjectiveAcceptance.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldAlphaSlice: {binding.PageBindDisplaysOfflineGeoworldAlphaSlice.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldAlphaExportPackage: {binding.PageBindDisplaysOfflineGeoworldAlphaExportPackage.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldAlphaManualAcceptance: {binding.PageBindDisplaysOfflineGeoworldAlphaManualAcceptance.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldAlphaManualResultIntake: {binding.PageBindDisplaysOfflineGeoworldAlphaManualResultIntake.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Source Health",
            string.Empty,
            $"- sourceHealthPassed: {qualityGate.SourceHealthPassed.ToString().ToLowerInvariant()}",
            $"- scannedCSharpFileCount: {qualityGate.ScannedCSharpFileCount}",
            $"- workspaceServiceLogicalLineCount: {qualityGate.WorkspaceServiceLogicalLineCount}",
            $"- maxLogicalLineCount: {qualityGate.MaxLogicalLineCount}",
            $"- maxPhysicalLineLength: {qualityGate.MaxPhysicalLineLength}",
            $"- filesOver1000LogicalLinesCount: {qualityGate.FilesOver1000LogicalLinesCount}",
            $"- filesOver700LogicalLinesInGoal092NamespaceCount: {qualityGate.FilesOver700LogicalLinesInGoal092NamespaceCount}",
            $"- zeroLfSourceCount: {qualityGate.ZeroLfSourceCount}",
            $"- crOnlySourceCount: {qualityGate.CrOnlySourceCount}",
            $"- rawPhysicalOneLineSourceCount: {qualityGate.RawPhysicalOneLineSourceCount}",
            $"- minifiedSourceCount: {qualityGate.MinifiedSourceCount}",
            string.Empty,
            "## Quality Gate",
            string.Empty,
            $"- qualityGatePassed: {qualityGate.Passed.ToString().ToLowerInvariant()}",
            $"- requiredArtifactGroupsPresent: {qualityGate.RequiredArtifactGroupsPresent.ToString().ToLowerInvariant()}",
            $"- goal091StreamWindowsVisible: {qualityGate.Goal091StreamWindowsVisible.ToString().ToLowerInvariant()}",
            $"- cacheExportGroupPresent: {qualityGate.CacheExportGroupPresent.ToString().ToLowerInvariant()}",
            $"- goal093FilesDiscoveredByRelativePaths: {qualityGate.Goal093FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- unityHandoffGroupPresent: {qualityGate.UnityHandoffGroupPresent.ToString().ToLowerInvariant()}",
            $"- unityProbeSourceInventoryPassed: {qualityGate.UnityProbeSourceInventoryPassed.ToString().ToLowerInvariant()}",
            $"- unitySimulatedReadProofPassed: {qualityGate.UnitySimulatedReadProofPassed.ToString().ToLowerInvariant()}",
            $"- unityNegativeProofPassed: {qualityGate.UnityNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- unityAlphaRuntimeBootstrapUnchanged: {qualityGate.UnityAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- unityForbiddenAreasUnchanged: {qualityGate.UnityForbiddenAreasUnchanged.ToString().ToLowerInvariant()}",
            $"- unityHandoffMetadataOnly: {qualityGate.UnityHandoffMetadataOnly.ToString().ToLowerInvariant()}",
            $"- unityPayloadHashesMatchGoal095Ledger: {qualityGate.UnityPayloadHashesMatchGoal095Ledger.ToString().ToLowerInvariant()}",
            $"- goal095FilesDiscoveredByRelativePaths: {qualityGate.Goal095FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- noUnityFilesChangedByGoal096: {qualityGate.NoUnityFilesChangedByGoal096.ToString().ToLowerInvariant()}",
            $"- geoworldGroupPresent: {qualityGate.GeoworldGroupPresent.ToString().ToLowerInvariant()}",
            $"- geoworldBoundaryPrefetchPassed: {qualityGate.GeoworldBoundaryPrefetchPassed.ToString().ToLowerInvariant()}",
            $"- geoworldTaxonomyCoveragePassed: {qualityGate.GeoworldTaxonomyCoveragePassed.ToString().ToLowerInvariant()}",
            $"- geoworldNegativeProofPassed: {qualityGate.GeoworldNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- geoworldQualityGatePassed: {qualityGate.GeoworldQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- geoworldOverviewVisible: {qualityGate.GeoworldOverviewVisible.ToString().ToLowerInvariant()}",
            $"- goal099FilesDiscoveredByRelativePaths: {qualityGate.Goal099FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffGroupPresent: {qualityGate.OfflineGeoworldHandoffGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffPackageCount: {qualityGate.OfflineGeoworldHandoffPackageCount}",
            $"- offlineGeoworldHandoffVisualCacheRecordCount: {qualityGate.OfflineGeoworldHandoffVisualCacheRecordCount}",
            $"- offlineGeoworldHandoffSimulatedReadProofPassed: {qualityGate.OfflineGeoworldHandoffSimulatedReadProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffNegativeProofPassed: {qualityGate.OfflineGeoworldHandoffNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldHandoffAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffQualityGatePassed: {qualityGate.OfflineGeoworldHandoffQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal100FilesDiscoveredByRelativePaths: {qualityGate.Goal100FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewGroupPresent: {qualityGate.OfflineGeoworldUnityPreviewGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewCommandCount: {qualityGate.OfflineGeoworldUnityPreviewCommandCount}",
            $"- offlineGeoworldUnityPreviewTravelWindowStepCount: {qualityGate.OfflineGeoworldUnityPreviewTravelWindowStepCount}",
            $"- offlineGeoworldUnityPreviewUnityScriptsReady: {qualityGate.OfflineGeoworldUnityPreviewUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewSimulatedCommandProofPassed: {qualityGate.OfflineGeoworldUnityPreviewSimulatedCommandProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewNegativeProofPassed: {qualityGate.OfflineGeoworldUnityPreviewNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldUnityPreviewAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityPreviewQualityGatePassed: {qualityGate.OfflineGeoworldUnityPreviewQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal101FilesDiscoveredByRelativePaths: {qualityGate.Goal101FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewGroupPresent: {qualityGate.OfflineGeoworldUnityEditorPreviewGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewCommandCount: {qualityGate.OfflineGeoworldUnityEditorPreviewCommandCount}",
            $"- offlineGeoworldUnityEditorPreviewTravelWindowStepCount: {qualityGate.OfflineGeoworldUnityEditorPreviewTravelWindowStepCount}",
            $"- offlineGeoworldUnityEditorPreviewExpectedObjectCount: {qualityGate.OfflineGeoworldUnityEditorPreviewExpectedObjectCount}",
            $"- offlineGeoworldUnityEditorPreviewEditorWindowScriptReady: {qualityGate.OfflineGeoworldUnityEditorPreviewEditorWindowScriptReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewSimulatedActionProofPassed: {qualityGate.OfflineGeoworldUnityEditorPreviewSimulatedActionProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewClearOperationProofPassed: {qualityGate.OfflineGeoworldUnityEditorPreviewClearOperationProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewNegativeProofPassed: {qualityGate.OfflineGeoworldUnityEditorPreviewNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldUnityEditorPreviewAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldUnityEditorPreviewQualityGatePassed: {qualityGate.OfflineGeoworldUnityEditorPreviewQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal102FilesDiscoveredByRelativePaths: {qualityGate.Goal102FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelGroupPresent: {qualityGate.OfflineGeoworldPlayModeTravelGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelStepCount: {qualityGate.OfflineGeoworldPlayModeTravelStepCount}",
            $"- offlineGeoworldPlayModeTravelObjectCount: {qualityGate.OfflineGeoworldPlayModeTravelObjectCount}",
            $"- offlineGeoworldPlayModeTravelUnityScriptsReady: {qualityGate.OfflineGeoworldPlayModeTravelUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelEditorWindowReady: {qualityGate.OfflineGeoworldPlayModeTravelEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelSimulatedExecutionProofPassed: {qualityGate.OfflineGeoworldPlayModeTravelSimulatedExecutionProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelNegativeProofPassed: {qualityGate.OfflineGeoworldPlayModeTravelNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelGoal102BClosureRecorded: {qualityGate.OfflineGeoworldPlayModeTravelGoal102BClosureRecorded.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldPlayModeTravelAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldPlayModeTravelQualityGatePassed: {qualityGate.OfflineGeoworldPlayModeTravelQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal103FilesDiscoveredByRelativePaths: {qualityGate.Goal103FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelGroupPresent: {qualityGate.OfflineGeoworldInteractiveTravelGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelMovementSampleCount: {qualityGate.OfflineGeoworldInteractiveTravelMovementSampleCount}",
            $"- offlineGeoworldInteractiveTravelBoundaryCrossingCount: {qualityGate.OfflineGeoworldInteractiveTravelBoundaryCrossingCount}",
            $"- offlineGeoworldInteractiveTravelObjectCount: {qualityGate.OfflineGeoworldInteractiveTravelObjectCount}",
            $"- offlineGeoworldInteractiveTravelUnityScriptsReady: {qualityGate.OfflineGeoworldInteractiveTravelUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelEditorWindowReady: {qualityGate.OfflineGeoworldInteractiveTravelEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelSimulatedExecutionProofPassed: {qualityGate.OfflineGeoworldInteractiveTravelSimulatedExecutionProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelNegativeProofPassed: {qualityGate.OfflineGeoworldInteractiveTravelNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldInteractiveTravelAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractiveTravelQualityGatePassed: {qualityGate.OfflineGeoworldInteractiveTravelQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal104FilesDiscoveredByRelativePaths: {qualityGate.Goal104FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionGroupPresent: {qualityGate.OfflineGeoworldInteractionGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionTargetCount: {qualityGate.OfflineGeoworldInteractionTargetCount}",
            $"- offlineGeoworldInteractionActionKindCount: {qualityGate.OfflineGeoworldInteractionActionKindCount}",
            $"- offlineGeoworldInteractionActionCount: {qualityGate.OfflineGeoworldInteractionActionCount}",
            $"- offlineGeoworldInteractionScriptedEventCount: {qualityGate.OfflineGeoworldInteractionScriptedEventCount}",
            $"- offlineGeoworldInteractionStateDeltaCount: {qualityGate.OfflineGeoworldInteractionStateDeltaCount}",
            $"- offlineGeoworldInteractionFinalStateHash: {qualityGate.OfflineGeoworldInteractionFinalStateHash}",
            $"- offlineGeoworldInteractionStateHashChainPassed: {qualityGate.OfflineGeoworldInteractionStateHashChainPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionUnityScriptsReady: {qualityGate.OfflineGeoworldInteractionUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionEditorWindowReady: {qualityGate.OfflineGeoworldInteractionEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionUnitySafetyScanPassed: {qualityGate.OfflineGeoworldInteractionUnitySafetyScanPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionSimulatedSessionProofPassed: {qualityGate.OfflineGeoworldInteractionSimulatedSessionProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionNegativeProofPassed: {qualityGate.OfflineGeoworldInteractionNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldInteractionAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldInteractionQualityGatePassed: {qualityGate.OfflineGeoworldInteractionQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal105FilesDiscoveredByRelativePaths: {qualityGate.Goal105FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionReplayGroupPresent: {qualityGate.OfflineGeoworldSessionReplayGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionReplayStepCount: {qualityGate.OfflineGeoworldSessionReplayStepCount}",
            $"- offlineGeoworldSessionStateDeltaCount: {qualityGate.OfflineGeoworldSessionStateDeltaCount}",
            $"- offlineGeoworldSessionCheckpointStepIndex: {qualityGate.OfflineGeoworldSessionCheckpointStepIndex}",
            $"- offlineGeoworldSessionAcceptanceChecklistStepCount: {qualityGate.OfflineGeoworldSessionAcceptanceChecklistStepCount}",
            $"- offlineGeoworldSessionUnityScriptsReady: {qualityGate.OfflineGeoworldSessionUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionEditorWindowReady: {qualityGate.OfflineGeoworldSessionEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionSimulatedReplayProofPassed: {qualityGate.OfflineGeoworldSessionSimulatedReplayProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionNegativeProofPassed: {qualityGate.OfflineGeoworldSessionNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldSessionAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldSessionQualityGatePassed: {qualityGate.OfflineGeoworldSessionQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal106FilesDiscoveredByRelativePaths: {qualityGate.Goal106FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveAcceptanceGroupPresent: {qualityGate.OfflineGeoworldObjectiveAcceptanceGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveCount: {qualityGate.OfflineGeoworldObjectiveCount}",
            $"- offlineGeoworldObjectiveCompletedCount: {qualityGate.OfflineGeoworldObjectiveCompletedCount}",
            $"- offlineGeoworldObjectivePayloadFileCount: {qualityGate.OfflineGeoworldObjectivePayloadFileCount}",
            $"- offlineGeoworldObjectiveUnityScriptsReady: {qualityGate.OfflineGeoworldObjectiveUnityScriptsReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveEditorWindowReady: {qualityGate.OfflineGeoworldObjectiveEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveReplayAcceptanceProofPassed: {qualityGate.OfflineGeoworldObjectiveReplayAcceptanceProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveNegativeProofPassed: {qualityGate.OfflineGeoworldObjectiveNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveAlphaQualityConsolidationPassed: {qualityGate.OfflineGeoworldObjectiveAlphaQualityConsolidationPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldObjectiveAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldObjectiveQualityGatePassed: {qualityGate.OfflineGeoworldObjectiveQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal107FilesDiscoveredByRelativePaths: {qualityGate.Goal107FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceGroupPresent: {qualityGate.OfflineGeoworldAlphaSliceGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceComponentCount: {qualityGate.OfflineGeoworldAlphaSliceComponentCount}",
            $"- offlineGeoworldAlphaSliceReadyComponentCount: {qualityGate.OfflineGeoworldAlphaSliceReadyComponentCount}",
            $"- offlineGeoworldAlphaSliceObjectiveCount: {qualityGate.OfflineGeoworldAlphaSliceObjectiveCount}",
            $"- offlineGeoworldAlphaSliceCompletedObjectiveCount: {qualityGate.OfflineGeoworldAlphaSliceCompletedObjectiveCount}",
            $"- offlineGeoworldAlphaSliceUnityToolReady: {qualityGate.OfflineGeoworldAlphaSliceUnityToolReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceAcceptanceRunbookReady: {qualityGate.OfflineGeoworldAlphaSliceAcceptanceRunbookReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceFinalProofPassed: {qualityGate.OfflineGeoworldAlphaSliceFinalProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceNegativeProofPassed: {qualityGate.OfflineGeoworldAlphaSliceNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldAlphaSliceAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaSliceQualityGatePassed: {qualityGate.OfflineGeoworldAlphaSliceQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal108FilesDiscoveredByRelativePaths: {qualityGate.Goal108FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportPackageGroupPresent: {qualityGate.OfflineGeoworldAlphaExportPackageGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportPackageFileCount: {qualityGate.OfflineGeoworldAlphaExportPackageFileCount}",
            $"- offlineGeoworldAlphaExportIndexedFileCount: {qualityGate.OfflineGeoworldAlphaExportIndexedFileCount}",
            $"- offlineGeoworldAlphaExportChecksumStatus: {qualityGate.OfflineGeoworldAlphaExportChecksumStatus}",
            $"- offlineGeoworldAlphaExportCleanImportProofPassed: {qualityGate.OfflineGeoworldAlphaExportCleanImportProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportNegativeProofPassed: {qualityGate.OfflineGeoworldAlphaExportNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportUnityVerifierReady: {qualityGate.OfflineGeoworldAlphaExportUnityVerifierReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportEditorWindowReady: {qualityGate.OfflineGeoworldAlphaExportEditorWindowReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportWorkspaceBindingPassed: {qualityGate.OfflineGeoworldAlphaExportWorkspaceBindingPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportSourceLineagePassed: {qualityGate.OfflineGeoworldAlphaExportSourceLineagePassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportAcceptanceGateStatus: {qualityGate.OfflineGeoworldAlphaExportAcceptanceGateStatus}",
            $"- offlineGeoworldAlphaExportAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldAlphaExportAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaExportQualityGatePassed: {qualityGate.OfflineGeoworldAlphaExportQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal109FilesDiscoveredByRelativePaths: {qualityGate.Goal109FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceGroupPresent: {qualityGate.OfflineGeoworldAlphaManualAcceptanceGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceChecklistStepCount: {qualityGate.OfflineGeoworldAlphaManualAcceptanceChecklistStepCount}",
            $"- offlineGeoworldAlphaManualAcceptancePayloadFileCount: {qualityGate.OfflineGeoworldAlphaManualAcceptancePayloadFileCount}",
            $"- offlineGeoworldAlphaManualAcceptanceExportFileCount: {qualityGate.OfflineGeoworldAlphaManualAcceptanceExportFileCount}",
            $"- offlineGeoworldAlphaManualAcceptanceAutomatedGatePassed: {qualityGate.OfflineGeoworldAlphaManualAcceptanceAutomatedGatePassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceManualPending: {qualityGate.OfflineGeoworldAlphaManualAcceptanceManualPending.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceUnityRunnerReady: {qualityGate.OfflineGeoworldAlphaManualAcceptanceUnityRunnerReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceSimulatedProofPassed: {qualityGate.OfflineGeoworldAlphaManualAcceptanceSimulatedProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceNegativeProofPassed: {qualityGate.OfflineGeoworldAlphaManualAcceptanceNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceWorkspaceBindingPassed: {qualityGate.OfflineGeoworldAlphaManualAcceptanceWorkspaceBindingPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldAlphaManualAcceptanceAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualAcceptanceQualityGatePassed: {qualityGate.OfflineGeoworldAlphaManualAcceptanceQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal110FilesDiscoveredByRelativePaths: {qualityGate.Goal110FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeGroupPresent: {qualityGate.OfflineGeoworldAlphaManualResultIntakeGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeDecisionStatus: {qualityGate.OfflineGeoworldAlphaManualResultIntakeDecisionStatus}",
            $"- offlineGeoworldAlphaManualResultIntakeGoal110PackagePresent: {qualityGate.OfflineGeoworldAlphaManualResultIntakeGoal110PackagePresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeResultFilePresent: {qualityGate.OfflineGeoworldAlphaManualResultIntakeResultFilePresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeAcceptableCandidate: {qualityGate.OfflineGeoworldAlphaManualResultIntakeAcceptableCandidate.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeAcceptedByCodex: {qualityGate.OfflineGeoworldAlphaManualResultIntakeAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeHumanAcceptanceStillRequired: {qualityGate.OfflineGeoworldAlphaManualResultIntakeHumanAcceptanceStillRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakeChecklistHashMatched: {qualityGate.OfflineGeoworldAlphaManualResultIntakeChecklistHashMatched.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultIntakePassedStepCount: {qualityGate.OfflineGeoworldAlphaManualResultIntakePassedStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeFailedStepCount: {qualityGate.OfflineGeoworldAlphaManualResultIntakeFailedStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakePendingStepCount: {qualityGate.OfflineGeoworldAlphaManualResultIntakePendingStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeSkippedStepCount: {qualityGate.OfflineGeoworldAlphaManualResultIntakeSkippedStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeMissingStepCount: {qualityGate.OfflineGeoworldAlphaManualResultIntakeMissingStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeDuplicateStepCount: {qualityGate.OfflineGeoworldAlphaManualResultIntakeDuplicateStepCount}",
            $"- offlineGeoworldAlphaManualResultIntakeQualityGatePassed: {qualityGate.OfflineGeoworldAlphaManualResultIntakeQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal111FilesDiscoveredByRelativePaths: {qualityGate.Goal111FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorPackGroupPresent: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorPackGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorStatus: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorStatus}",
            $"- offlineGeoworldAlphaAcceptanceOperatorGoal111DecisionStatus: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorGoal111DecisionStatus}",
            $"- offlineGeoworldAlphaAcceptanceOperatorManualResultPresent: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorManualResultPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorManualResultAvailableForHumanReview: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorManualResultAvailableForHumanReview.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorAcceptedByCodex: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorHumanAcceptanceStillRequired: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorHumanAcceptanceStillRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorChecklistStepCount: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorChecklistStepCount}",
            $"- offlineGeoworldAlphaAcceptanceOperatorChecklistHashPresent: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorChecklistHashPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaAcceptanceOperatorQualityGatePassed: {qualityGate.OfflineGeoworldAlphaAcceptanceOperatorQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal112FilesDiscoveredByRelativePaths: {qualityGate.Goal112FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchGroupPresent: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchStatus: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchStatus}",
            $"- offlineGeoworldAlphaManualResultWorkbenchGoal111DecisionStatus: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchGoal111DecisionStatus}",
            $"- offlineGeoworldAlphaManualResultWorkbenchGoal112OperatorStatus: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchGoal112OperatorStatus}",
            $"- offlineGeoworldAlphaManualResultWorkbenchManualResultPresent: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchManualResultPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchAcceptedByCodex: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchHumanAcceptanceStillRequired: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchHumanAcceptanceStillRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchDraftTemplateOnly: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchDraftTemplateOnly.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchChecklistStepCount: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchChecklistStepCount}",
            $"- offlineGeoworldAlphaManualResultWorkbenchChecklistHashPresent: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchChecklistHashPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualResultWorkbenchQualityGatePassed: {qualityGate.OfflineGeoworldAlphaManualResultWorkbenchQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal113FilesDiscoveredByRelativePaths: {qualityGate.Goal113FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationGroupPresent: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationDecisionStatus: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationDecisionStatus}",
            $"- offlineGeoworldAlphaHumanResultRevalidationGoal111DecisionStatus: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationGoal111DecisionStatus}",
            $"- offlineGeoworldAlphaHumanResultRevalidationManualResultPresent: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationManualResultPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationManualResultJsonValid: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationManualResultJsonValid.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationAcceptableCandidate: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationAcceptableCandidate.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationRecommendedHumanDecision: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationRecommendedHumanDecision}",
            $"- offlineGeoworldAlphaHumanResultRevalidationAcceptedByCodex: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationHumanAcceptanceStillRequired: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationHumanAcceptanceStillRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationManualGateRemainsHumanDecision: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationManualGateRemainsHumanDecision.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationRequiredStepCount: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationRequiredStepCount}",
            $"- offlineGeoworldAlphaHumanResultRevalidationPassedStepCount: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationPassedStepCount}",
            $"- offlineGeoworldAlphaHumanResultRevalidationManualInputNotCommitted: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationManualInputNotCommitted.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaHumanResultRevalidationQualityGatePassed: {qualityGate.OfflineGeoworldAlphaHumanResultRevalidationQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal115FilesDiscoveredByRelativePaths: {qualityGate.Goal115FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceGroupPresent: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceManualGate: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceManualGate}",
            $"- offlineGeoworldAlphaManualGateAcceptanceManualGateStatus: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceManualGateStatus}",
            $"- offlineGeoworldAlphaManualGateAcceptanceHumanAccepted: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceHumanAccepted.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceHumanDecisionStatement: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceHumanDecisionStatement}",
            $"- offlineGeoworldAlphaManualGateAcceptanceSourceDecisionStatus: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceSourceDecisionStatus}",
            $"- offlineGeoworldAlphaManualGateAcceptanceManualResultSha256: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceManualResultSha256}",
            $"- offlineGeoworldAlphaManualGateAcceptanceAcceptedByCodex: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceAcceptedByCodex.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceManualInputNotCommitted: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceManualInputNotCommitted.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceRawManualResultEmbeddedInArtifacts: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceRawManualResultEmbeddedInArtifacts.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceRecommendedNextDecision: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceRecommendedNextDecision}",
            $"- offlineGeoworldAlphaManualGateAcceptanceNotFinalReleaseOrRuntimeBuild: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceNotFinalReleaseOrRuntimeBuild.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceNoRuntimeProviderOrNetworkChanges: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceNoRuntimeProviderOrNetworkChanges.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceNoUnityFileChangesRequired: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceNoUnityFileChangesRequired.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaManualGateAcceptanceRequiredStepCount: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceRequiredStepCount}",
            $"- offlineGeoworldAlphaManualGateAcceptancePassedStepCount: {qualityGate.OfflineGeoworldAlphaManualGateAcceptancePassedStepCount}",
            $"- offlineGeoworldAlphaManualGateAcceptanceQualityGatePassed: {qualityGate.OfflineGeoworldAlphaManualGateAcceptanceQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal116FilesDiscoveredByRelativePaths: {qualityGate.Goal116FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaPostAcceptanceContinuationGroupPresent: {qualityGate.OfflineGeoworldAlphaPostAcceptanceContinuationGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaPostAcceptanceManualGateStatus: {qualityGate.OfflineGeoworldAlphaPostAcceptanceManualGateStatus}",
            $"- offlineGeoworldAlphaPostAcceptanceHumanAccepted: {qualityGate.OfflineGeoworldAlphaPostAcceptanceHumanAccepted.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaPostAcceptanceManualResultSha256: {qualityGate.OfflineGeoworldAlphaPostAcceptanceManualResultSha256}",
            $"- offlineGeoworldAlphaPostAcceptanceRecommendedNextLane: {qualityGate.OfflineGeoworldAlphaPostAcceptanceRecommendedNextLane}",
            $"- offlineGeoworldAlphaPostAcceptanceRecommendedNextGoalId: {qualityGate.OfflineGeoworldAlphaPostAcceptanceRecommendedNextGoalId}",
            $"- offlineGeoworldAlphaPostAcceptanceReadyLaneCount: {qualityGate.OfflineGeoworldAlphaPostAcceptanceReadyLaneCount}",
            $"- offlineGeoworldAlphaPostAcceptanceCandidateLaneCount: {qualityGate.OfflineGeoworldAlphaPostAcceptanceCandidateLaneCount}",
            $"- offlineGeoworldAlphaPostAcceptanceBlockedLaneCount: {qualityGate.OfflineGeoworldAlphaPostAcceptanceBlockedLaneCount}",
            $"- offlineGeoworldAlphaPostAcceptanceDoNotStartAutomatically: {qualityGate.OfflineGeoworldAlphaPostAcceptanceDoNotStartAutomatically.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAlphaPostAcceptanceQualityGatePassed: {qualityGate.OfflineGeoworldAlphaPostAcceptanceQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal117FilesDiscoveredByRelativePaths: {qualityGate.Goal117FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAcceptedAlphaBaselineGroupPresent: {qualityGate.OfflineGeoworldAcceptedAlphaBaselineGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAcceptedAlphaBaselineId: {qualityGate.OfflineGeoworldAcceptedAlphaBaselineId}",
            $"- offlineGeoworldAcceptedAlphaBaselineHash: {qualityGate.OfflineGeoworldAcceptedAlphaBaselineHash}",
            $"- offlineGeoworldAcceptedAlphaBaselineReady: {qualityGate.OfflineGeoworldAcceptedAlphaBaselineReady.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAcceptedAlphaManualGateStatus: {qualityGate.OfflineGeoworldAcceptedAlphaManualGateStatus}",
            $"- offlineGeoworldAcceptedAlphaRecommendedNextDecision: {qualityGate.OfflineGeoworldAcceptedAlphaRecommendedNextDecision}",
            $"- offlineGeoworldAcceptedAlphaIncludedSourceGoalCount: {qualityGate.OfflineGeoworldAcceptedAlphaIncludedSourceGoalCount}",
            $"- offlineGeoworldAcceptedAlphaAcceptedEvidenceRootCount: {qualityGate.OfflineGeoworldAcceptedAlphaAcceptedEvidenceRootCount}",
            $"- offlineGeoworldAcceptedAlphaProducedOnlyRootCount: {qualityGate.OfflineGeoworldAcceptedAlphaProducedOnlyRootCount}",
            $"- offlineGeoworldAcceptedAlphaBlockedOrSupersededNoteCount: {qualityGate.OfflineGeoworldAcceptedAlphaBlockedOrSupersededNoteCount}",
            $"- offlineGeoworldAcceptedAlphaDoNotStartAutomatically: {qualityGate.OfflineGeoworldAcceptedAlphaDoNotStartAutomatically.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldAcceptedAlphaQualityGatePassed: {qualityGate.OfflineGeoworldAcceptedAlphaQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal118FilesDiscoveredByRelativePaths: {qualityGate.Goal118FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- noAbsolutePaths: {qualityGate.NoAbsolutePaths.ToString().ToLowerInvariant()}",
            $"- noBinaryOrRasterMediaAdded: {qualityGate.NoBinaryOrRasterMediaAdded.ToString().ToLowerInvariant()}",
            $"- noRuntimeUnityProviderSchemaProjectDependencyChanges: {qualityGate.NoRuntimeUnityProviderSchemaProjectDependencyChanges.ToString().ToLowerInvariant()}",
            $"- noPromptDumps: {qualityGate.NoPromptDumps.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Artifact Hashes",
            string.Empty,
            $"- catalogHash: {report.CatalogHash}",
            $"- proofStatusHash: {report.ProofStatusHash}",
            $"- winFormsBindingInventoryHash: {report.WinFormsBindingInventoryHash}",
            $"- qualityGateHash: {report.QualityGateHash}"
        ]);
        AddGoal119ReportLines(lines, report);
        AddGoal119QualityLines(lines, qualityGate);
        AddGoal120ReportLines(lines, report);
        AddGoal120QualityLines(lines, qualityGate);
        AddGoal121ReportLines(lines, report);
        AddGoal121QualityLines(lines, qualityGate);
        AddGoal122ReportLines(lines, report);
        AddGoal122QualityLines(lines, qualityGate);
        AddGoal123ReportLines(lines, report);
        AddGoal123QualityLines(lines, qualityGate);
        AddGoal124ReportLines(lines, report);
        AddGoal124QualityLines(lines, qualityGate);
        AddGoal125ReportLines(lines, report);
        AddGoal125QualityLines(lines, qualityGate);
        AddGoal126ReportLines(lines, report); AddGoal126QualityLines(lines, qualityGate);
        AddGoal127ReportLines(lines, report); AddGoal127QualityLines(lines, qualityGate);
        AddGoal128ReportLines(lines, report); AddGoal128QualityLines(lines, qualityGate);
        AddGoal129ReportLines(lines, report); AddGoal129QualityLines(lines, qualityGate);
        AddGoal130ReportLines(lines, report); AddGoal130QualityLines(lines, qualityGate);
        return string.Join(Environment.NewLine, lines) + Environment.NewLine;
    }
}
