namespace LLMGameCreator.Application.Design.VisualWorldStreamPreviewWorkspace;

public sealed partial class VisualWorldStreamPreviewWorkspaceService
{
    private static string RenderWorkspaceReport(
        VisualWorldStreamPreviewWorkspaceReport report,
        VisualWorldStreamPreviewCatalog catalog,
        VisualWorldStreamPreviewProofStatusDocument proofStatus,
        VisualWorldPreviewWinFormsBindingInventory binding,
        VisualWorldPreviewWorkspaceQualityGate qualityGate,
        string deterministicReportHash)
    {
        var lines = new List<string>
        {
            "# Goal 096 Unity Handoff Inspector Probe Readiness Report",
            string.Empty,
            $"- implementationStatus: {report.ImplementationStatus}",
            $"- accepted: {report.Accepted.ToString().ToLowerInvariant()}",
            $"- manualGate: {report.ManualGate} required",
            $"- deterministicReportHash: {deterministicReportHash}",
            string.Empty,
            "## Summary",
            string.Empty,
            "Goal 096 extends the existing BCL-only Visual World Stream Preview Workspace so editor review can inspect Goal 095 Unity StreamingAssets handoff readiness without launching Unity. It loads real Goal 095 evidence and mirrored payload files by repository-relative path, compares hashes against the Goal 095 ledgers, and does not change Runtime, Unity behavior, providers, schema, project files, dependencies, binary media or raster media.",
            string.Empty,
            "## Catalog",
            string.Empty,
            $"- groupCount: {catalog.GroupCount}",
            $"- entryCount: {catalog.EntryCount}",
            $"- svgTextPreviewCount: {catalog.SvgTextPreviewCount}",
            $"- goal091StreamWindowEntryCount: {qualityGate.Goal091StreamWindowEntryCount}",
            string.Empty
        };
        lines.AddRange(catalog.Groups.Select(group =>
            "- " + group.GroupId + ": entries=" + group.EntryCount
            + ", svgEntries=" + group.SvgEntryCount
            + ", sourceGoal=" + group.SourceGoalId
            + ", status=" + group.Status));
        lines.AddRange(
        [
            string.Empty,
            "## Cache Export Inspector",
            string.Empty,
            $"- cacheExportPackageCount: {report.CacheExportPackageCount}",
            $"- cacheExportRecordCount: {report.CacheExportRecordCount}",
            $"- cacheExportSourceChunkCount: {report.CacheExportSourceChunkCount}",
            $"- cacheExportStreamWindowCount: {report.CacheExportStreamWindowCount}",
            $"- runtimeHandoffSidecarVisible: {report.RuntimeHandoffSidecarVisible.ToString().ToLowerInvariant()}",
            $"- runtimeHandoffSidecarMetadataOnly: {report.RuntimeHandoffSidecarMetadataOnly.ToString().ToLowerInvariant()}",
            $"- cacheReadbackProofPassed: {report.CacheReadbackProofPassed.ToString().ToLowerInvariant()}",
            $"- cacheOverlapReuseProofPassed: {report.CacheOverlapReuseProofPassed.ToString().ToLowerInvariant()}",
            $"- cacheNegativeProofPassed: {report.CacheNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- cacheInvalidationMatrixPassed: {report.CacheInvalidationMatrixPassed.ToString().ToLowerInvariant()}",
            $"- cacheNoRawFullWorldDump: {report.CacheNoRawFullWorldDump.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Unity Handoff Inspector",
            string.Empty,
            $"- unityPayloadFileCount: {report.UnityPayloadFileCount}",
            $"- unityPackageCount: {report.UnityPackageCount}",
            $"- unityExportRecordCount: {report.UnityExportRecordCount}",
            $"- unityStreamWindowCount: {report.UnityStreamWindowCount}",
            $"- unityUniqueChunkKeyCount: {report.UnityUniqueChunkKeyCount}",
            $"- unityProbeSourceInventoryVisible: {report.UnityProbeSourceInventoryVisible.ToString().ToLowerInvariant()}",
            $"- unityProbeSourceInventoryPassed: {report.UnityProbeSourceInventoryPassed.ToString().ToLowerInvariant()}",
            $"- unitySimulatedReadProofPassed: {report.UnitySimulatedReadProofPassed.ToString().ToLowerInvariant()}",
            $"- unityNegativeProofPassed: {report.UnityNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- unityAlphaRuntimeBootstrapUnchanged: {report.UnityAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- unityForbiddenAreasUnchanged: {report.UnityForbiddenAreasUnchanged.ToString().ToLowerInvariant()}",
            $"- unityHandoffMetadataOnly: {report.UnityHandoffMetadataOnly.ToString().ToLowerInvariant()}",
            $"- unityPayloadHashesMatchGoal095Ledger: {report.UnityPayloadHashesMatchGoal095Ledger.ToString().ToLowerInvariant()}",
            $"- goal095FilesDiscoveredByRelativePaths: {report.Goal095FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- noUnityFilesChangedByGoal096: {report.NoUnityFilesChangedByGoal096.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Geoworld Inspector",
            string.Empty,
            $"- geoworldOfflineBundleId: {report.GeoworldOfflineBundleId}",
            $"- geoworldNormalizedFeatureCount: {report.GeoworldNormalizedFeatureCount}",
            $"- geoworldWorldSourceGraphChunkCount: {report.GeoworldWorldSourceGraphChunkCount}",
            $"- geoworldStreamWindowChunkCount: {report.GeoworldStreamWindowChunkCount}",
            $"- geoworldBoundaryPrefetchPassed: {report.GeoworldBoundaryPrefetchPassed.ToString().ToLowerInvariant()}",
            $"- geoworldNegativeProofPassed: {report.GeoworldNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- geoworldQualityGatePassed: {report.GeoworldQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal099FilesDiscoveredByRelativePaths: {report.Goal099FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Offline Geoworld Handoff",
            string.Empty,
            $"- offlineGeoworldHandoffPackageCount: {report.OfflineGeoworldHandoffPackageCount}",
            $"- offlineGeoworldHandoffFeatureCount: {report.OfflineGeoworldHandoffFeatureCount}",
            $"- offlineGeoworldHandoffVisualCacheRecordCount: {report.OfflineGeoworldHandoffVisualCacheRecordCount}",
            $"- offlineGeoworldHandoffSourceChunkCount: {report.OfflineGeoworldHandoffSourceChunkCount}",
            $"- offlineGeoworldHandoffStreamWindowChunkCount: {report.OfflineGeoworldHandoffStreamWindowChunkCount}",
            $"- offlineGeoworldHandoffUnityPayloadFileCount: {report.OfflineGeoworldHandoffUnityPayloadFileCount}",
            $"- offlineGeoworldHandoffFeatureKindCounts: {report.OfflineGeoworldHandoffFeatureKindCountsSummary}",
            $"- offlineGeoworldHandoffSimulatedReadProofPassed: {report.OfflineGeoworldHandoffSimulatedReadProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffNegativeProofPassed: {report.OfflineGeoworldHandoffNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffAlphaRuntimeBootstrapUnchanged: {report.OfflineGeoworldHandoffAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffQualityGatePassed: {report.OfflineGeoworldHandoffQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal100FilesDiscoveredByRelativePaths: {report.Goal100FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Proof Status",
            string.Empty,
            $"- proofStatusPassed: {proofStatus.Passed.ToString().ToLowerInvariant()}",
            $"- proofCount: {proofStatus.ProofCount}"
        ]);
        lines.AddRange(proofStatus.Proofs.Select(proof =>
            "- " + proof.ProofId + ": passed=" + proof.Passed.ToString().ToLowerInvariant()
            + ", path=" + proof.RelativePath));
        lines.AddRange(
        [
            string.Empty,
            "## WinForms Binding",
            string.Empty,
            $"- bindingPassed: {binding.Passed.ToString().ToLowerInvariant()}",
            $"- pageControlExists: {binding.PageControlExists.ToString().ToLowerInvariant()}",
            $"- designerExists: {binding.DesignerExists.ToString().ToLowerInvariant()}",
            $"- compositionRootRegistersService: {binding.CompositionRootRegistersService.ToString().ToLowerInvariant()}",
            $"- compositionRootRegistersPage: {binding.CompositionRootRegistersPage.ToString().ToLowerInvariant()}",
            $"- editorRegistryIncludesPage: {binding.EditorRegistryIncludesPage.ToString().ToLowerInvariant()}",
            $"- pageActivationLoadsApplicationResult: {binding.PageActivationLoadsApplicationResult.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysGroupsEntriesProofs: {binding.PageBindDisplaysGroupsEntriesProofs.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysCacheExports: {binding.PageBindDisplaysCacheExports.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysUnityHandoff: {binding.PageBindDisplaysUnityHandoff.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysGeoworld: {binding.PageBindDisplaysGeoworld.ToString().ToLowerInvariant()}",
            $"- pageBindDisplaysOfflineGeoworldHandoff: {binding.PageBindDisplaysOfflineGeoworldHandoff.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Source Health",
            string.Empty,
            $"- sourceHealthPassed: {qualityGate.SourceHealthPassed.ToString().ToLowerInvariant()}",
            $"- scannedCSharpFileCount: {qualityGate.ScannedCSharpFileCount}",
            $"- workspaceServiceLogicalLineCount: {qualityGate.WorkspaceServiceLogicalLineCount}",
            $"- maxLogicalLineCount: {qualityGate.MaxLogicalLineCount}",
            $"- maxPhysicalLineLength: {qualityGate.MaxPhysicalLineLength}",
            $"- filesOver1000LogicalLinesCount: {qualityGate.FilesOver1000LogicalLinesCount}",
            $"- filesOver700LogicalLinesInGoal092NamespaceCount: {qualityGate.FilesOver700LogicalLinesInGoal092NamespaceCount}",
            $"- zeroLfSourceCount: {qualityGate.ZeroLfSourceCount}",
            $"- crOnlySourceCount: {qualityGate.CrOnlySourceCount}",
            $"- rawPhysicalOneLineSourceCount: {qualityGate.RawPhysicalOneLineSourceCount}",
            $"- minifiedSourceCount: {qualityGate.MinifiedSourceCount}",
            string.Empty,
            "## Quality Gate",
            string.Empty,
            $"- qualityGatePassed: {qualityGate.Passed.ToString().ToLowerInvariant()}",
            $"- requiredArtifactGroupsPresent: {qualityGate.RequiredArtifactGroupsPresent.ToString().ToLowerInvariant()}",
            $"- goal091StreamWindowsVisible: {qualityGate.Goal091StreamWindowsVisible.ToString().ToLowerInvariant()}",
            $"- cacheExportGroupPresent: {qualityGate.CacheExportGroupPresent.ToString().ToLowerInvariant()}",
            $"- goal093FilesDiscoveredByRelativePaths: {qualityGate.Goal093FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- unityHandoffGroupPresent: {qualityGate.UnityHandoffGroupPresent.ToString().ToLowerInvariant()}",
            $"- unityProbeSourceInventoryPassed: {qualityGate.UnityProbeSourceInventoryPassed.ToString().ToLowerInvariant()}",
            $"- unitySimulatedReadProofPassed: {qualityGate.UnitySimulatedReadProofPassed.ToString().ToLowerInvariant()}",
            $"- unityNegativeProofPassed: {qualityGate.UnityNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- unityAlphaRuntimeBootstrapUnchanged: {qualityGate.UnityAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- unityForbiddenAreasUnchanged: {qualityGate.UnityForbiddenAreasUnchanged.ToString().ToLowerInvariant()}",
            $"- unityHandoffMetadataOnly: {qualityGate.UnityHandoffMetadataOnly.ToString().ToLowerInvariant()}",
            $"- unityPayloadHashesMatchGoal095Ledger: {qualityGate.UnityPayloadHashesMatchGoal095Ledger.ToString().ToLowerInvariant()}",
            $"- goal095FilesDiscoveredByRelativePaths: {qualityGate.Goal095FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- noUnityFilesChangedByGoal096: {qualityGate.NoUnityFilesChangedByGoal096.ToString().ToLowerInvariant()}",
            $"- geoworldGroupPresent: {qualityGate.GeoworldGroupPresent.ToString().ToLowerInvariant()}",
            $"- geoworldBoundaryPrefetchPassed: {qualityGate.GeoworldBoundaryPrefetchPassed.ToString().ToLowerInvariant()}",
            $"- geoworldTaxonomyCoveragePassed: {qualityGate.GeoworldTaxonomyCoveragePassed.ToString().ToLowerInvariant()}",
            $"- geoworldNegativeProofPassed: {qualityGate.GeoworldNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- geoworldQualityGatePassed: {qualityGate.GeoworldQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- geoworldOverviewVisible: {qualityGate.GeoworldOverviewVisible.ToString().ToLowerInvariant()}",
            $"- goal099FilesDiscoveredByRelativePaths: {qualityGate.Goal099FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffGroupPresent: {qualityGate.OfflineGeoworldHandoffGroupPresent.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffPackageCount: {qualityGate.OfflineGeoworldHandoffPackageCount}",
            $"- offlineGeoworldHandoffVisualCacheRecordCount: {qualityGate.OfflineGeoworldHandoffVisualCacheRecordCount}",
            $"- offlineGeoworldHandoffSimulatedReadProofPassed: {qualityGate.OfflineGeoworldHandoffSimulatedReadProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffNegativeProofPassed: {qualityGate.OfflineGeoworldHandoffNegativeProofPassed.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffAlphaRuntimeBootstrapUnchanged: {qualityGate.OfflineGeoworldHandoffAlphaRuntimeBootstrapUnchanged.ToString().ToLowerInvariant()}",
            $"- offlineGeoworldHandoffQualityGatePassed: {qualityGate.OfflineGeoworldHandoffQualityGatePassed.ToString().ToLowerInvariant()}",
            $"- goal100FilesDiscoveredByRelativePaths: {qualityGate.Goal100FilesDiscoveredByRelativePaths.ToString().ToLowerInvariant()}",
            $"- noAbsolutePaths: {qualityGate.NoAbsolutePaths.ToString().ToLowerInvariant()}",
            $"- noBinaryOrRasterMediaAdded: {qualityGate.NoBinaryOrRasterMediaAdded.ToString().ToLowerInvariant()}",
            $"- noRuntimeUnityProviderSchemaProjectDependencyChanges: {qualityGate.NoRuntimeUnityProviderSchemaProjectDependencyChanges.ToString().ToLowerInvariant()}",
            $"- noPromptDumps: {qualityGate.NoPromptDumps.ToString().ToLowerInvariant()}",
            string.Empty,
            "## Artifact Hashes",
            string.Empty,
            $"- catalogHash: {report.CatalogHash}",
            $"- proofStatusHash: {report.ProofStatusHash}",
            $"- winFormsBindingInventoryHash: {report.WinFormsBindingInventoryHash}",
            $"- qualityGateHash: {report.QualityGateHash}"
        ]);
        return string.Join(Environment.NewLine, lines) + Environment.NewLine;
    }
}
