namespace LLMGameCreator.Application.Design.SemanticArtifactContracts;

public static class SemanticArtifactContractRegistry
{
    public static IReadOnlyList<SemanticArtifactContractDescriptor> BuildDefaultContracts() =>
    [
        Contract(
            "game_profile_v1",
            "Game profile and style family",
            "profile",
            "profile",
            ["game_profile_v1"],
            [],
            ["profile", "style"],
            ["profile_contract", "semantic_dependent"],
            [],
            [],
            "profile_contract",
            "goal_021_profile_contract",
            "ready",
            "sacr.profile",
            "Accepted profile contract input for deterministic planning."),
        Contract(
            "capability_bundle_pipeline_inputs_v1",
            "Capability bundle pipeline inputs",
            "capability",
            "planning",
            ["capability_bundle_pipeline_inputs_v1"],
            ["game_profile_v1"],
            ["profile", "capability"],
            ["capability_bundle", "semantic_dependent"],
            [],
            ["game_profile_v1"],
            "capability_bundle_pipeline",
            "goal_023_capability_bundle_pipeline_inputs",
            "ready",
            "sacr.capability",
            "Accepted deterministic bridge from profile choices to generator pipeline inputs."),
        Contract(
            "semantic_pack_v1",
            "Semantic pack and semantic catalog",
            "semantic",
            "semantic_catalog",
            ["semantic_pack_v1", "semantic_catalog_v1"],
            ["game_profile_v1"],
            ["profile", "tone", "world", "actor", "quest", "dialogue", "item", "combat", "settlement"],
            ["semantic_pack", "semantic_dependent"],
            [],
            ["game_profile_v1"],
            "semantic_catalog",
            "goal_005_semantic_pack_contract",
            "ready",
            "sacr.semantic",
            "Compiled authoring semantics used by deterministic generator planning."),
        Contract(
            "world_topology_region_route_graph_v1",
            "World topology, region graph and route graph",
            "world_topology",
            "world",
            ["world_topology_v1", "region_graph_v1", "route_graph_v1"],
            ["game_profile_v1", "semantic_pack_v1", "capability_bundle_pipeline_inputs_v1"],
            ["world", "topology"],
            ["world_generation", "semantic_dependent"],
            [],
            ["game_profile_v1", "semantic_pack_v1", "capability_bundle_pipeline_inputs_v1"],
            "package_assembly_world_entities",
            "package_assembly_world_entities",
            "ready",
            "sacr.world",
            "Planning contract for selected world and route graph artifact families."),
        Contract(
            "biome_weather_hazard_event_hints_v1",
            "Biome, weather, hazard and event hints",
            "biome_event_hints",
            "world",
            ["biome_pack_v1", "weather_hint_pack_v1", "hazard_hint_pack_v1", "event_hint_pack_v1"],
            ["semantic_pack_v1", "world_topology_v1"],
            ["world", "biome", "event"],
            ["biome_generation", "semantic_dependent"],
            [],
            ["semantic_pack_v1", "world_topology_region_route_graph_v1"],
            "world_biome_candidate",
            "candidate_world_biome_noise_v1",
            "optional",
            "sacr.biome",
            "Optional planning hints for later biome and event expansion."),
        Contract(
            "entity_archetype_npc_actor_profile_v1",
            "Entity archetype and NPC actor profile",
            "actor_profile",
            "actors",
            ["entity_archetype_pack_v1", "npc_actor_profile_v1"],
            ["semantic_pack_v1", "world_topology_v1"],
            ["actor", "world"],
            ["entity_generation", "npc_generation", "semantic_dependent"],
            [],
            ["semantic_pack_v1", "world_topology_region_route_graph_v1"],
            "package_assembly_world_entities",
            "package_assembly_world_entities",
            "ready",
            "sacr.actor",
            "Ready planning contract for actor and NPC artifact families."),
        Contract(
            "faction_reputation_social_relation_v1",
            "Faction, reputation and social relation",
            "faction_relation",
            "factions",
            ["faction_pack_v1", "reputation_track_v1", "social_relation_pack_v1"],
            ["semantic_pack_v1", "entity_archetype_pack_v1"],
            ["actor", "faction", "social"],
            ["faction_generation", "semantic_dependent"],
            [],
            ["semantic_pack_v1", "entity_archetype_npc_actor_profile_v1"],
            "package_assembly_world_entities",
            "package_assembly_world_entities",
            "ready",
            "sacr.faction",
            "Ready planning contract for faction and relation expansion."),
        Contract(
            "dialogue_string_table_localization_hint_v1",
            "Dialogue, string table and localization hint",
            "dialogue_localization",
            "dialogue",
            ["dialogue_pack_v1", "string_table_hint_v1", "localization_hint_v1"],
            ["semantic_pack_v1", "npc_actor_profile_v1", "faction_pack_v1"],
            ["dialogue", "tone", "actor"],
            ["dialogue_generation", "localization_hint", "semantic_dependent"],
            [],
            ["semantic_pack_v1", "entity_archetype_npc_actor_profile_v1", "faction_reputation_social_relation_v1"],
            "package_assembly_dialogue_quests",
            "package_assembly_dialogue_quests",
            "ready",
            "sacr.dialogue",
            "Ready planning contract for dialogue and localization hints."),
        Contract(
            "quest_graph_objective_reward_pattern_v1",
            "Quest graph, objective and reward pattern",
            "quest_pattern",
            "quests",
            ["quest_graph_v1", "objective_pattern_v1", "reward_pattern_v1"],
            ["semantic_pack_v1", "dialogue_pack_v1", "item_pack_v1"],
            ["quest", "dialogue", "item"],
            ["quest_generation", "semantic_dependent"],
            [],
            ["semantic_pack_v1", "dialogue_string_table_localization_hint_v1", "item_resource_recipe_loot_economy_v1"],
            "package_assembly_dialogue_quests",
            "package_assembly_dialogue_quests",
            "ready",
            "sacr.quest",
            "Ready planning contract for quest graph and reward pattern expansion."),
        Contract(
            "item_resource_recipe_loot_economy_v1",
            "Item, resource, recipe, loot and economy",
            "item_economy",
            "items",
            ["item_pack_v1", "resource_pack_v1", "recipe_pack_v1", "loot_pack_v1", "economy_pack_v1"],
            ["semantic_pack_v1"],
            ["item", "economy"],
            ["item_generation", "economy_generation", "semantic_dependent"],
            [],
            ["semantic_pack_v1"],
            "package_assembly_items_economy_crafting",
            "package_assembly_items_economy_crafting",
            "ready",
            "sacr.item",
            "Ready planning contract for item and economy artifact families."),
        Contract(
            "combat_progression_ability_v1",
            "Combat, progression and ability",
            "combat_progression",
            "combat",
            ["combat_pack_v1", "progression_pack_v1", "ability_pack_v1", "status_pack_v1"],
            ["semantic_pack_v1", "item_pack_v1", "npc_actor_profile_v1"],
            ["combat", "progression", "actor"],
            ["combat_generation", "progression_generation", "semantic_dependent"],
            [],
            ["semantic_pack_v1", "item_resource_recipe_loot_economy_v1", "entity_archetype_npc_actor_profile_v1"],
            "package_assembly_combat_progression",
            "package_assembly_combat_progression",
            "ready",
            "sacr.combat",
            "Ready planning contract for combat and progression artifact families."),
        Contract(
            "settlement_building_landmark_v1",
            "Settlement, building and landmark",
            "settlement_landmark",
            "world",
            ["settlement_pack_v1", "building_pack_v1", "landmark_pack_v1"],
            ["semantic_pack_v1", "region_graph_v1"],
            ["settlement", "world"],
            ["settlement_generation", "semantic_dependent"],
            [],
            ["semantic_pack_v1", "world_topology_region_route_graph_v1"],
            "settlement_candidate",
            "future_settlement_module",
            "future_required",
            "sacr.settlement",
            "Future required planning contract; no current module promotion."),
        Contract(
            "presentation_export_ir_v1",
            "Presentation and export IR",
            "presentation_export_ir",
            "presentation",
            ["presentation_ir_v1", "export_profile_ir_v1"],
            ["game_profile_v1", "semantic_pack_v1"],
            ["presentation", "profile"],
            ["presentation_ir", "export_ir", "semantic_dependent"],
            [],
            ["game_profile_v1", "semantic_pack_v1"],
            "presentation_ir_candidate",
            "future_presentation_export_module",
            "future_required",
            "sacr.presentation",
            "Future optional planning IR only; no view or player implementation is changed by Goal 030.")
    ];

    public static IReadOnlyList<SemanticPackDescriptor> BuildDefaultSemanticPacks() =>
    [
        Pack(
            "semantic_pack/core_generator_spine",
            ["frontier_survival", "gothic_intrigue", "caravan_trade"],
            ["profile", "capability", "world", "topology", "actor", "quest", "dialogue", "item", "combat", "progression", "tone"],
            ["core", "deterministic", "generator_spine"],
            ["requires:profile", "implies:contract_registry"],
            ["actor_archetype", "quest_pattern", "dialogue_hint", "item_hint", "combat_hint"],
            [],
            ["settlement_landmark"],
            "000-core"),
        Pack(
            "semantic_pack/frontier_survival",
            ["frontier_survival"],
            ["world", "biome", "event", "actor", "faction", "quest", "item", "combat", "settlement"],
            ["frontier", "survival", "hazard", "resource_scarcity"],
            ["hostile_to:wilderness", "produced_by:salvage"],
            ["biome_hazard", "resource_loot", "settlement_landmark"],
            [],
            ["settlement_buildings"],
            "100-frontier"),
        Pack(
            "semantic_pack/gothic_intrigue",
            ["gothic_intrigue"],
            ["tone", "dialogue", "quest", "actor", "faction", "social", "item"],
            ["gothic", "intrigue", "secrets", "reputation"],
            ["hostile_to:rival_house", "implies:clue_dialogue"],
            ["dialogue_tone", "faction_relation", "quest_motive"],
            ["open_world_hazard_density"],
            ["dialogue_clue_graph"],
            "100-gothic"),
        Pack(
            "semantic_pack/caravan_trade",
            ["caravan_trade"],
            ["world", "route", "item", "economy", "dialogue", "faction", "quest", "settlement"],
            ["caravan", "trade", "route", "market"],
            ["produced_by:trade_route", "consumed_by:settlement"],
            ["route_landmark", "vendor_economy", "quest_delivery"],
            [],
            ["vendor_economy_deep_sim"],
            "100-caravan")
    ];

    public static IReadOnlySet<string> DefaultAvailableModuleIds { get; } = new HashSet<string>(
        BuildDefaultContracts()
            .Where(contract => contract.LifecycleStatus is "ready" or "optional")
            .Select(contract => contract.ModuleId),
        StringComparer.Ordinal);

    private static SemanticArtifactContractDescriptor Contract(
        string id,
        string displayName,
        string artifactKind,
        string domain,
        IReadOnlyList<string> produced,
        IReadOnlyList<string> consumed,
        IReadOnlyList<string> requiredScopes,
        IReadOnlyList<string> capabilityTags,
        IReadOnlyList<string> compatibilityTags,
        IReadOnlyList<string> dependencies,
        string moduleOwner,
        string moduleId,
        string lifecycleStatus,
        string diagnosticPrefix,
        string notes) =>
        new()
        {
            ContractId = id,
            DisplayName = displayName,
            Version = "1.0.0",
            ArtifactKind = artifactKind,
            Domain = domain,
            ProducedArtifactTypes = produced,
            ConsumedArtifactTypes = consumed,
            RequiredSemanticScopes = requiredScopes,
            CapabilityTags = capabilityTags,
            CompatibilityTags = compatibilityTags,
            Dependencies = dependencies,
            ModuleOwner = moduleOwner,
            ModuleId = moduleId,
            LifecycleStatus = lifecycleStatus,
            DiagnosticCodePrefix = diagnosticPrefix,
            Notes = notes
        };

    private static SemanticPackDescriptor Pack(
        string packId,
        IReadOnlyList<string> supportedProfileIds,
        IReadOnlyList<string> scopes,
        IReadOnlyList<string> tags,
        IReadOnlyList<string> relations,
        IReadOnlyList<string> expansions,
        IReadOnlyList<string> blocked,
        IReadOnlyList<string> future,
        string orderingKey) =>
        new()
        {
            PackId = packId,
            SupportedProfileIds = supportedProfileIds,
            SemanticScopes = scopes,
            SemanticTags = tags,
            RelationHints = relations,
            ExpansionHints = expansions,
            BlockedCapabilityHints = blocked,
            FutureCapabilityHints = future,
            OrderingKey = orderingKey
        };
}
