using LLMGameCreator.Application.Play.GeneratedCampaign;
using LLMGameCreator.Runtime.Abstractions;

namespace LLMGameCreator.WinForms.Pages;

public sealed partial class GeneratedCampaignPageControl : UserControl, IEditorPage
{
    private readonly GeneratedCampaignSessionService? _service;
    public GeneratedCampaignPageControl(){InitializeComponent();}
    public GeneratedCampaignPageControl(GeneratedCampaignSessionService service){_service=service;InitializeComponent();_map.CellClicked+=MapCellClicked;}
    public string Id=>"generated-campaign-player"; public string Title=>"Играть"; public int SortOrder=>54; Control IEditorPage.View=>this;
    public void OnActivated()=>Bind(_service?.Refresh());
    private void NewGameClick(object? sender,EventArgs e)=>Bind(_service?.StartNew());
    private void SaveClick(object? sender,EventArgs e)=>Bind(_service?.Save(_slot.Text));
    private void ContinueClick(object? sender,EventArgs e){if(_service is null)return;using var dialog=new GeneratedCampaignSavePickerDialog(_service.ListSaves().Entries);if(dialog.ShowDialog(this)!=DialogResult.OK||dialog.SelectedEntry is null)return;if(dialog.MigrateRequested){var preview=_service.PreviewMigration(dialog.SelectedEntry.SlotName);Bind(_service.MigrateAndContinue(preview));}else Bind(_service.Continue(dialog.SelectedEntry.SlotName));}
    private void MapCellClicked(object? sender,(int X,int Y) cell){var snapshot=_service?.Refresh();if(snapshot?.Map is null)return;var player=snapshot.Map.Cells.SingleOrDefault(x=>x.PlayerPresent);if(player is null||Math.Abs(player.X-cell.X)+Math.Abs(player.Y-cell.Y)!=1)return;var kind=cell.X>player.X?GeneratedCampaignActionKind.MoveRight:cell.X<player.X?GeneratedCampaignActionKind.MoveLeft:cell.Y>player.Y?GeneratedCampaignActionKind.MoveDown:GeneratedCampaignActionKind.MoveUp;var action=snapshot.Actions.FirstOrDefault(x=>x.Kind==kind&&x.Enabled);if(action is not null)Bind(_service!.Execute(action.ActionId));}
    protected override bool ProcessCmdKey(ref Message msg,Keys keyData){if(ContainsFocus&&ActiveControl is TextBoxBase)return base.ProcessCmdKey(ref msg,keyData);var snapshot=_service?.Refresh();if(snapshot is null)return base.ProcessCmdKey(ref msg,keyData);var kind=keyData switch{Keys.W or Keys.Up=>GeneratedCampaignActionKind.MoveUp,Keys.S or Keys.Down=>GeneratedCampaignActionKind.MoveDown,Keys.A or Keys.Left=>GeneratedCampaignActionKind.MoveLeft,Keys.D or Keys.Right=>GeneratedCampaignActionKind.MoveRight,Keys.E or Keys.Enter=>GeneratedCampaignActionKind.Interact,_=>(GeneratedCampaignActionKind)(-1)};var action=snapshot.Actions.FirstOrDefault(x=>x.Kind==kind&&x.Enabled);if(action is null)return base.ProcessCmdKey(ref msg,keyData);Bind(_service!.Execute(action.ActionId));return true;}
    private void Bind(GeneratedCampaignSnapshot? snapshot){if(snapshot is null)return;_status.Text=$"{snapshot.ProjectTitle} — {snapshot.CurrentRegionTitle} — {snapshot.StatusTitle}";_map.Projection=snapshot.Map;_actions.SuspendLayout();_actions.Controls.Clear();foreach(var action in snapshot.Actions){var button=new Button{Text=action.Title,AutoSize=true,Enabled=action.Enabled,Tag=action.ActionId,AccessibleDescription=action.Description};new ToolTip().SetToolTip(button,action.Description+(action.Enabled?string.Empty:" — "+action.DisabledReason));button.Click+=(sender,_)=>{if(sender is Button { Tag: string actionId }) Bind(_service?.Execute(actionId));};_actions.Controls.Add(button);}_actions.ResumeLayout();WriteTab(0,snapshot.Resources.Concat(snapshot.Stats).Concat(snapshot.Progressions));WriteTab(1,snapshot.ActiveQuests);WriteTab(2,snapshot.Inventory.Concat(snapshot.Equipment).Concat(snapshot.Factions));WriteTab(3,snapshot.RecentEvents.Select(x=>new GeneratedCampaignTextRow{Title=x}));_technical.Text=string.Join(Environment.NewLine,snapshot.TechnicalDetails.Select(x=>$"{x.Key}: {x.Value}").Concat(snapshot.Diagnostics));_map.Invalidate();}
    private void WriteTab(int index,IEnumerable<GeneratedCampaignTextRow> rows){var tab=_hud.TabPages[index];tab.Controls.Clear();tab.Controls.Add(new Label{Dock=DockStyle.Top,AutoSize=true,MaximumSize=new Size(300,0),Text=string.Join(Environment.NewLine,rows.Select(r=>string.IsNullOrWhiteSpace(r.Value)?r.Title:r.Title+": "+r.Value))});}
}
