#nullable disable

using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace LLMGameCreator.WinForms.Pages
{
    partial class GenerationPageControl
    {
        private IContainer components;
        private TableLayoutPanel _rootLayout;
        private TableLayoutPanel _topLayout;
        private TabControl _briefTabs;
        private TabPage _coreTabPage;
        private TabPage _advancedTabPage;
        private TabPage _scopeTabPage;
        private TableLayoutPanel _coreLayout;
        private TableLayoutPanel _advancedLayout;
        private TableLayoutPanel _scopeLayout;
        private TableLayoutPanel _buttonLayout;
        private SplitContainer _outputSplitContainer;
        private Label _profileLabel;
        private Label _profileValueLabel;
        private Label _currentPackageLabel;
        private Label _ideaLabel;
        private TextBox _ideaTextBox;
        private Label _genreLabel;
        private ComboBox _genreComboBox;
        private Label _toneLabel;
        private ComboBox _toneComboBox;
        private Label _cameraLabel;
        private ComboBox _cameraComboBox;
        private Label _settingLabel;
        private ComboBox _settingComboBox;
        private Label _conflictLabel;
        private ComboBox _conflictComboBox;
        private Label _playerRoleLabel;
        private TextBox _playerRoleTextBox;
        private Label _requiredNpcLabel;
        private TextBox _requiredNpcTextBox;
        private Label _firstLocationLabel;
        private TextBox _firstLocationTextBox;
        private Label _mapSizeLabel;
        private FlowLayoutPanel _mapSizePanel;
        private NumericUpDown _mapWidthNumeric;
        private Label _mapSizeSeparatorLabel;
        private NumericUpDown _mapHeightNumeric;
        private Label _loreLabel;
        private TextBox _loreTextBox;
        private Label _hardConstraintsLabel;
        private TextBox _hardConstraintsTextBox;
        private Label _mustIncludeLabel;
        private TextBox _mustIncludeTextBox;
        private Label _mustAvoidLabel;
        private TextBox _mustAvoidTextBox;
        private Label _playerFantasyLabel;
        private TextBox _playerFantasyTextBox;
        private Label _gameplayLogicLabel;
        private TextBox _gameplayLogicTextBox;
        private Label _maxTileOverridesLabel;
        private NumericUpDown _maxTileOverridesNumeric;
        private Label _targetNpcLabel;
        private NumericUpDown _targetNpcNumeric;
        private Label _targetEntityLabel;
        private NumericUpDown _targetEntityNumeric;
        private Label _targetQuestLabel;
        private NumericUpDown _targetQuestNumeric;
        private Label _targetDialogueLabel;
        private NumericUpDown _targetDialogueNumeric;
        private Label _detailModeLabel;
        private ComboBox _detailModeComboBox;
        private Label _logicModeLabel;
        private ComboBox _logicModeComboBox;
        private Button _testLmStudioButton;
        private Button _aiHelperButton;
        private Button _generateButton;
        private Button _applyButton;
        private Button _saveButton;
        private Button _validateButton;
        private Button _cancelButton;
        private Label _statusLabel;
        private TextBox _rawJsonTextBox;
        private TextBox _resultTextBox;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_currentGamePackageService != null)
                {
                    _currentGamePackageService.CurrentChanged -= CurrentGamePackageService_CurrentChanged;
                }

                components?.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            this._rootLayout = new TableLayoutPanel();
            this._topLayout = new TableLayoutPanel();
            this._profileLabel = new Label();
            this._profileValueLabel = new Label();
            this._currentPackageLabel = new Label();
            this._briefTabs = new TabControl();
            this._coreTabPage = new TabPage();
            this._advancedTabPage = new TabPage();
            this._scopeTabPage = new TabPage();
            this._coreLayout = new TableLayoutPanel();
            this._advancedLayout = new TableLayoutPanel();
            this._scopeLayout = new TableLayoutPanel();
            this._ideaLabel = new Label();
            this._ideaTextBox = new TextBox();
            this._genreLabel = new Label();
            this._genreComboBox = new ComboBox();
            this._toneLabel = new Label();
            this._toneComboBox = new ComboBox();
            this._cameraLabel = new Label();
            this._cameraComboBox = new ComboBox();
            this._settingLabel = new Label();
            this._settingComboBox = new ComboBox();
            this._conflictLabel = new Label();
            this._conflictComboBox = new ComboBox();
            this._playerRoleLabel = new Label();
            this._playerRoleTextBox = new TextBox();
            this._requiredNpcLabel = new Label();
            this._requiredNpcTextBox = new TextBox();
            this._firstLocationLabel = new Label();
            this._firstLocationTextBox = new TextBox();
            this._mapSizeLabel = new Label();
            this._mapSizePanel = new FlowLayoutPanel();
            this._mapWidthNumeric = new NumericUpDown();
            this._mapSizeSeparatorLabel = new Label();
            this._mapHeightNumeric = new NumericUpDown();
            this._loreLabel = new Label();
            this._loreTextBox = new TextBox();
            this._hardConstraintsLabel = new Label();
            this._hardConstraintsTextBox = new TextBox();
            this._mustIncludeLabel = new Label();
            this._mustIncludeTextBox = new TextBox();
            this._mustAvoidLabel = new Label();
            this._mustAvoidTextBox = new TextBox();
            this._playerFantasyLabel = new Label();
            this._playerFantasyTextBox = new TextBox();
            this._gameplayLogicLabel = new Label();
            this._gameplayLogicTextBox = new TextBox();
            this._maxTileOverridesLabel = new Label();
            this._maxTileOverridesNumeric = new NumericUpDown();
            this._targetNpcLabel = new Label();
            this._targetNpcNumeric = new NumericUpDown();
            this._targetEntityLabel = new Label();
            this._targetEntityNumeric = new NumericUpDown();
            this._targetQuestLabel = new Label();
            this._targetQuestNumeric = new NumericUpDown();
            this._targetDialogueLabel = new Label();
            this._targetDialogueNumeric = new NumericUpDown();
            this._detailModeLabel = new Label();
            this._detailModeComboBox = new ComboBox();
            this._logicModeLabel = new Label();
            this._logicModeComboBox = new ComboBox();
            this._buttonLayout = new TableLayoutPanel();
            this._testLmStudioButton = new Button();
            this._aiHelperButton = new Button();
            this._generateButton = new Button();
            this._applyButton = new Button();
            this._saveButton = new Button();
            this._validateButton = new Button();
            this._cancelButton = new Button();
            this._statusLabel = new Label();
            this._outputSplitContainer = new SplitContainer();
            this._rawJsonTextBox = new TextBox();
            this._resultTextBox = new TextBox();
            this._rootLayout.SuspendLayout();
            this._topLayout.SuspendLayout();
            this._briefTabs.SuspendLayout();
            this._coreTabPage.SuspendLayout();
            this._advancedTabPage.SuspendLayout();
            this._scopeTabPage.SuspendLayout();
            this._coreLayout.SuspendLayout();
            this._advancedLayout.SuspendLayout();
            this._scopeLayout.SuspendLayout();
            this._mapSizePanel.SuspendLayout();
            ((ISupportInitialize)(this._mapWidthNumeric)).BeginInit();
            ((ISupportInitialize)(this._mapHeightNumeric)).BeginInit();
            ((ISupportInitialize)(this._maxTileOverridesNumeric)).BeginInit();
            ((ISupportInitialize)(this._targetNpcNumeric)).BeginInit();
            ((ISupportInitialize)(this._targetEntityNumeric)).BeginInit();
            ((ISupportInitialize)(this._targetQuestNumeric)).BeginInit();
            ((ISupportInitialize)(this._targetDialogueNumeric)).BeginInit();
            this._buttonLayout.SuspendLayout();
            ((ISupportInitialize)(this._outputSplitContainer)).BeginInit();
            this._outputSplitContainer.Panel1.SuspendLayout();
            this._outputSplitContainer.Panel2.SuspendLayout();
            this._outputSplitContainer.SuspendLayout();
            this.SuspendLayout();
            // 
            // _rootLayout
            // 
            this._rootLayout.ColumnCount = 1;
            this._rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this._rootLayout.Controls.Add(this._topLayout, 0, 0);
            this._rootLayout.Controls.Add(this._briefTabs, 0, 1);
            this._rootLayout.Controls.Add(this._buttonLayout, 0, 2);
            this._rootLayout.Controls.Add(this._outputSplitContainer, 0, 3);
            this._rootLayout.Dock = DockStyle.Fill;
            this._rootLayout.Location = new Point(0, 0);
            this._rootLayout.Name = "_rootLayout";
            this._rootLayout.Padding = new Padding(8);
            this._rootLayout.RowCount = 4;
            this._rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
            this._rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 268F));
            this._rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
            this._rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this._rootLayout.Size = new Size(1100, 760);
            this._rootLayout.TabIndex = 0;
            // 
            // _topLayout
            // 
            this._topLayout.ColumnCount = 2;
            this._topLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F));
            this._topLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this._topLayout.Controls.Add(this._profileLabel, 0, 0);
            this._topLayout.Controls.Add(this._profileValueLabel, 1, 0);
            this._topLayout.Controls.Add(this._currentPackageLabel, 0, 1);
            this._topLayout.Dock = DockStyle.Fill;
            this._topLayout.RowCount = 2;
            this._topLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this._topLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this._topLayout.TabIndex = 0;
            this._profileLabel.Dock = DockStyle.Fill;
            this._profileLabel.Text = "LLM profile:";
            this._profileLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._profileValueLabel.AutoEllipsis = true;
            this._profileValueLabel.Dock = DockStyle.Fill;
            this._profileValueLabel.Text = "Загрузка...";
            this._profileValueLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._currentPackageLabel.AutoEllipsis = true;
            this._topLayout.SetColumnSpan(this._currentPackageLabel, 2);
            this._currentPackageLabel.Dock = DockStyle.Fill;
            this._currentPackageLabel.Text = "Проект игры не открыт.";
            this._currentPackageLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _briefTabs
            // 
            this._briefTabs.Controls.Add(this._coreTabPage);
            this._briefTabs.Controls.Add(this._advancedTabPage);
            this._briefTabs.Controls.Add(this._scopeTabPage);
            this._briefTabs.Dock = DockStyle.Fill;
            this._briefTabs.Location = new Point(11, 69);
            this._briefTabs.Name = "_briefTabs";
            this._briefTabs.SelectedIndex = 0;
            this._briefTabs.Size = new Size(1078, 262);
            this._briefTabs.TabIndex = 1;
            this._coreTabPage.Controls.Add(this._coreLayout);
            this._coreTabPage.Location = new Point(4, 24);
            this._coreTabPage.Name = "_coreTabPage";
            this._coreTabPage.Padding = new Padding(8);
            this._coreTabPage.Size = new Size(1070, 234);
            this._coreTabPage.TabIndex = 0;
            this._coreTabPage.Text = "Основные поля";
            this._coreTabPage.UseVisualStyleBackColor = true;
            this._advancedTabPage.Controls.Add(this._advancedLayout);
            this._advancedTabPage.Location = new Point(4, 24);
            this._advancedTabPage.Name = "_advancedTabPage";
            this._advancedTabPage.Padding = new Padding(8);
            this._advancedTabPage.Size = new Size(1070, 234);
            this._advancedTabPage.TabIndex = 1;
            this._advancedTabPage.Text = "Расширенный brief";
            this._advancedTabPage.UseVisualStyleBackColor = true;
            this._scopeTabPage.Controls.Add(this._scopeLayout);
            this._scopeTabPage.Location = new Point(4, 24);
            this._scopeTabPage.Name = "_scopeTabPage";
            this._scopeTabPage.Padding = new Padding(8);
            this._scopeTabPage.Size = new Size(1070, 234);
            this._scopeTabPage.TabIndex = 2;
            this._scopeTabPage.Text = "Scope и логика";
            this._scopeTabPage.UseVisualStyleBackColor = true;
            // 
            // _coreLayout
            // 
            this._coreLayout.ColumnCount = 4;
            this._coreLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 210F));
            this._coreLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._coreLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 210F));
            this._coreLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._coreLayout.Controls.Add(this._ideaLabel, 0, 0);
            this._coreLayout.Controls.Add(this._ideaTextBox, 1, 0);
            this._coreLayout.Controls.Add(this._genreLabel, 0, 1);
            this._coreLayout.Controls.Add(this._genreComboBox, 1, 1);
            this._coreLayout.Controls.Add(this._toneLabel, 2, 1);
            this._coreLayout.Controls.Add(this._toneComboBox, 3, 1);
            this._coreLayout.Controls.Add(this._cameraLabel, 0, 2);
            this._coreLayout.Controls.Add(this._cameraComboBox, 1, 2);
            this._coreLayout.Controls.Add(this._settingLabel, 2, 2);
            this._coreLayout.Controls.Add(this._settingComboBox, 3, 2);
            this._coreLayout.Controls.Add(this._conflictLabel, 0, 3);
            this._coreLayout.Controls.Add(this._conflictComboBox, 1, 3);
            this._coreLayout.Controls.Add(this._playerRoleLabel, 2, 3);
            this._coreLayout.Controls.Add(this._playerRoleTextBox, 3, 3);
            this._coreLayout.Controls.Add(this._requiredNpcLabel, 0, 4);
            this._coreLayout.Controls.Add(this._requiredNpcTextBox, 1, 4);
            this._coreLayout.Controls.Add(this._firstLocationLabel, 2, 4);
            this._coreLayout.Controls.Add(this._firstLocationTextBox, 3, 4);
            this._coreLayout.Controls.Add(this._mapSizeLabel, 0, 5);
            this._coreLayout.Controls.Add(this._mapSizePanel, 1, 5);
            this._coreLayout.Dock = DockStyle.Fill;
            this._coreLayout.RowCount = 6;
            this._coreLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 62F));
            this._coreLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this._coreLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this._coreLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this._coreLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this._coreLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            this._coreLayout.TabIndex = 0;
            this._ideaLabel.Dock = DockStyle.Fill;
            this._ideaLabel.Text = "Идея:";
            this._ideaLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._coreLayout.SetColumnSpan(this._ideaTextBox, 3);
            this._ideaTextBox.Dock = DockStyle.Fill;
            this._ideaTextBox.Multiline = true;
            this._ideaTextBox.ScrollBars = ScrollBars.Vertical;
            this._ideaTextBox.Text = "Небольшое приключение с понятной первой задачей и исследуемой стартовой локацией.";
            this._genreLabel.Dock = DockStyle.Fill;
            this._genreLabel.Text = "Жанр: механический жанр / gameplay expectation";
            this._genreLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._genreComboBox.Dock = DockStyle.Fill;
            this._genreComboBox.DropDownStyle = ComboBoxStyle.DropDown;
            this._genreComboBox.Items.AddRange(new object[] { "rpg", "adventure", "survival", "visual novel", "tactical rpg", "exploration", "mystery", "horror", "sandbox" });
            this._genreComboBox.Text = "rpg";
            this._toneLabel.Dock = DockStyle.Fill;
            this._toneLabel.Text = "Тон: эмоциональный стиль";
            this._toneLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._toneComboBox.Dock = DockStyle.Fill;
            this._toneComboBox.DropDownStyle = ComboBoxStyle.DropDown;
            this._toneComboBox.Items.AddRange(new object[] { "dark fantasy", "grimdark", "dark fairy tale", "mystery", "hopeful", "tense", "cozy", "comedic", "horror", "melancholic" });
            this._toneComboBox.Text = "dark fantasy";
            this._cameraLabel.Dock = DockStyle.Fill;
            this._cameraLabel.Text = "Камера: как смотреть на игру";
            this._cameraLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._cameraComboBox.Dock = DockStyle.Fill;
            this._cameraComboBox.DropDownStyle = ComboBoxStyle.DropDown;
            this._cameraComboBox.Items.AddRange(new object[] { "top-down grid", "side-view", "visual novel", "first person text", "tactical map", "isometric-like grid" });
            this._cameraComboBox.Text = "top-down grid";
            this._settingLabel.Dock = DockStyle.Fill;
            this._settingLabel.Text = "Сеттинг: тип мира/локации";
            this._settingLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._settingComboBox.Dock = DockStyle.Fill;
            this._settingComboBox.DropDownStyle = ComboBoxStyle.DropDown;
            this._settingComboBox.Items.AddRange(new object[] { "cursed village", "post-apocalyptic town", "fantasy city", "dungeon", "forest frontier", "cyberpunk district", "space station", "prison camp", "haunted manor" });
            this._settingComboBox.Text = "cursed village";
            this._conflictLabel.Dock = DockStyle.Fill;
            this._conflictLabel.Text = "Первый конфликт: первая проблема playable slice";
            this._conflictLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._conflictComboBox.Dock = DockStyle.Fill;
            this._conflictComboBox.DropDownStyle = ComboBoxStyle.DropDown;
            this._conflictComboBox.Items.AddRange(new object[] { "blocked road", "missing person", "cursed object", "monster near village", "locked gate", "poisoned well", "forbidden ruins", "stolen relic", "broken bridge", "suspicious stranger" });
            this._conflictComboBox.Text = "blocked road";
            this._playerRoleLabel.Dock = DockStyle.Fill;
            this._playerRoleLabel.Text = "Роль игрока:";
            this._playerRoleLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._playerRoleTextBox.Dock = DockStyle.Fill;
            this._playerRoleTextBox.Text = "новый смотритель дороги";
            this._requiredNpcLabel.Dock = DockStyle.Fill;
            this._requiredNpcLabel.Text = "NPC: обязательно добавить как prototype/entity/speaker";
            this._requiredNpcLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._requiredNpcTextBox.Dock = DockStyle.Fill;
            this._requiredNpcTextBox.Text = "староста";
            this._firstLocationLabel.Dock = DockStyle.Fill;
            this._firstLocationLabel.Text = "Первая локация: где стартует первая карта";
            this._firstLocationLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._firstLocationTextBox.Dock = DockStyle.Fill;
            this._firstLocationTextBox.Text = "стартовая деревня";
            this._mapSizeLabel.Dock = DockStyle.Fill;
            this._mapSizeLabel.Text = "Размер карты:";
            this._mapSizeLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._mapSizePanel.Controls.Add(this._mapWidthNumeric);
            this._mapSizePanel.Controls.Add(this._mapSizeSeparatorLabel);
            this._mapSizePanel.Controls.Add(this._mapHeightNumeric);
            this._mapSizePanel.Dock = DockStyle.Fill;
            this._mapSizePanel.WrapContents = false;
            this._mapWidthNumeric.Maximum = new decimal(new int[] { 40, 0, 0, 0 });
            this._mapWidthNumeric.Minimum = new decimal(new int[] { 12, 0, 0, 0 });
            this._mapWidthNumeric.Size = new Size(70, 23);
            this._mapWidthNumeric.Value = new decimal(new int[] { 24, 0, 0, 0 });
            this._mapSizeSeparatorLabel.AutoSize = true;
            this._mapSizeSeparatorLabel.Text = "x";
            this._mapSizeSeparatorLabel.TextAlign = ContentAlignment.MiddleCenter;
            this._mapHeightNumeric.Maximum = new decimal(new int[] { 30, 0, 0, 0 });
            this._mapHeightNumeric.Minimum = new decimal(new int[] { 8, 0, 0, 0 });
            this._mapHeightNumeric.Size = new Size(70, 23);
            this._mapHeightNumeric.Value = new decimal(new int[] { 16, 0, 0, 0 });
            // 
            // _advancedLayout
            // 
            this._advancedLayout.ColumnCount = 4;
            this._advancedLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 170F));
            this._advancedLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._advancedLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 170F));
            this._advancedLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._advancedLayout.Controls.Add(this._loreLabel, 0, 0);
            this._advancedLayout.Controls.Add(this._loreTextBox, 1, 0);
            this._advancedLayout.Controls.Add(this._hardConstraintsLabel, 2, 0);
            this._advancedLayout.Controls.Add(this._hardConstraintsTextBox, 3, 0);
            this._advancedLayout.Controls.Add(this._mustIncludeLabel, 0, 1);
            this._advancedLayout.Controls.Add(this._mustIncludeTextBox, 1, 1);
            this._advancedLayout.Controls.Add(this._mustAvoidLabel, 2, 1);
            this._advancedLayout.Controls.Add(this._mustAvoidTextBox, 3, 1);
            this._advancedLayout.Controls.Add(this._playerFantasyLabel, 0, 2);
            this._advancedLayout.Controls.Add(this._playerFantasyTextBox, 1, 2);
            this._advancedLayout.Controls.Add(this._gameplayLogicLabel, 2, 2);
            this._advancedLayout.Controls.Add(this._gameplayLogicTextBox, 3, 2);
            this._advancedLayout.Dock = DockStyle.Fill;
            this._advancedLayout.RowCount = 3;
            this._advancedLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 33.333F));
            this._advancedLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 33.333F));
            this._advancedLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 33.334F));
            this._loreLabel.Dock = DockStyle.Fill;
            this._loreLabel.Text = "Лор / уже существующие факты";
            this._loreLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._loreTextBox.Dock = DockStyle.Fill;
            this._loreTextBox.Multiline = true;
            this._loreTextBox.ScrollBars = ScrollBars.Vertical;
            this._hardConstraintsLabel.Dock = DockStyle.Fill;
            this._hardConstraintsLabel.Text = "Жёсткие ограничения";
            this._hardConstraintsLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._hardConstraintsTextBox.Dock = DockStyle.Fill;
            this._hardConstraintsTextBox.Multiline = true;
            this._hardConstraintsTextBox.ScrollBars = ScrollBars.Vertical;
            this._mustIncludeLabel.Dock = DockStyle.Fill;
            this._mustIncludeLabel.Text = "Обязательно включить";
            this._mustIncludeLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._mustIncludeTextBox.Dock = DockStyle.Fill;
            this._mustIncludeTextBox.Multiline = true;
            this._mustIncludeTextBox.ScrollBars = ScrollBars.Vertical;
            this._mustAvoidLabel.Dock = DockStyle.Fill;
            this._mustAvoidLabel.Text = "Запрещено / избегать";
            this._mustAvoidLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._mustAvoidTextBox.Dock = DockStyle.Fill;
            this._mustAvoidTextBox.Multiline = true;
            this._mustAvoidTextBox.ScrollBars = ScrollBars.Vertical;
            this._playerFantasyLabel.Dock = DockStyle.Fill;
            this._playerFantasyLabel.Text = "Что должен чувствовать/делать игрок";
            this._playerFantasyLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._playerFantasyTextBox.Dock = DockStyle.Fill;
            this._playerFantasyTextBox.Multiline = true;
            this._playerFantasyTextBox.ScrollBars = ScrollBars.Vertical;
            this._gameplayLogicLabel.Dock = DockStyle.Fill;
            this._gameplayLogicLabel.Text = "Логика геймплея / будущие Lua hooks";
            this._gameplayLogicLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._gameplayLogicTextBox.Dock = DockStyle.Fill;
            this._gameplayLogicTextBox.Multiline = true;
            this._gameplayLogicTextBox.ScrollBars = ScrollBars.Vertical;
            // 
            // _scopeLayout
            // 
            this._scopeLayout.ColumnCount = 4;
            this._scopeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
            this._scopeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._scopeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 180F));
            this._scopeLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
            this._scopeLayout.Controls.Add(this._maxTileOverridesLabel, 0, 0);
            this._scopeLayout.Controls.Add(this._maxTileOverridesNumeric, 1, 0);
            this._scopeLayout.Controls.Add(this._targetNpcLabel, 2, 0);
            this._scopeLayout.Controls.Add(this._targetNpcNumeric, 3, 0);
            this._scopeLayout.Controls.Add(this._targetEntityLabel, 0, 1);
            this._scopeLayout.Controls.Add(this._targetEntityNumeric, 1, 1);
            this._scopeLayout.Controls.Add(this._targetQuestLabel, 2, 1);
            this._scopeLayout.Controls.Add(this._targetQuestNumeric, 3, 1);
            this._scopeLayout.Controls.Add(this._targetDialogueLabel, 0, 2);
            this._scopeLayout.Controls.Add(this._targetDialogueNumeric, 1, 2);
            this._scopeLayout.Controls.Add(this._detailModeLabel, 2, 2);
            this._scopeLayout.Controls.Add(this._detailModeComboBox, 3, 2);
            this._scopeLayout.Controls.Add(this._logicModeLabel, 0, 3);
            this._scopeLayout.Controls.Add(this._logicModeComboBox, 1, 3);
            this._scopeLayout.Dock = DockStyle.Fill;
            this._scopeLayout.RowCount = 5;
            this._scopeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            this._scopeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            this._scopeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            this._scopeLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            this._scopeLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this._maxTileOverridesLabel.Dock = DockStyle.Fill;
            this._maxTileOverridesLabel.Text = "Max tile overrides:";
            this._maxTileOverridesLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._maxTileOverridesNumeric.Dock = DockStyle.Left;
            this._maxTileOverridesNumeric.Maximum = new decimal(new int[] { 160, 0, 0, 0 });
            this._maxTileOverridesNumeric.Minimum = new decimal(new int[] { 10, 0, 0, 0 });
            this._maxTileOverridesNumeric.Value = new decimal(new int[] { 40, 0, 0, 0 });
            this._targetNpcLabel.Dock = DockStyle.Fill;
            this._targetNpcLabel.Text = "Target NPC prototypes:";
            this._targetNpcLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._targetNpcNumeric.Dock = DockStyle.Left;
            this._targetNpcNumeric.Maximum = new decimal(new int[] { 6, 0, 0, 0 });
            this._targetNpcNumeric.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            this._targetNpcNumeric.Value = new decimal(new int[] { 2, 0, 0, 0 });
            this._targetEntityLabel.Dock = DockStyle.Fill;
            this._targetEntityLabel.Text = "Target entity instances:";
            this._targetEntityLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._targetEntityNumeric.Dock = DockStyle.Left;
            this._targetEntityNumeric.Maximum = new decimal(new int[] { 20, 0, 0, 0 });
            this._targetEntityNumeric.Value = new decimal(new int[] { 3, 0, 0, 0 });
            this._targetQuestLabel.Dock = DockStyle.Fill;
            this._targetQuestLabel.Text = "Target quests:";
            this._targetQuestLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._targetQuestNumeric.Dock = DockStyle.Left;
            this._targetQuestNumeric.Maximum = new decimal(new int[] { 3, 0, 0, 0 });
            this._targetQuestNumeric.Value = new decimal(new int[] { 1, 0, 0, 0 });
            this._targetDialogueLabel.Dock = DockStyle.Fill;
            this._targetDialogueLabel.Text = "Target dialogues:";
            this._targetDialogueLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._targetDialogueNumeric.Dock = DockStyle.Left;
            this._targetDialogueNumeric.Maximum = new decimal(new int[] { 3, 0, 0, 0 });
            this._targetDialogueNumeric.Value = new decimal(new int[] { 1, 0, 0, 0 });
            this._detailModeLabel.Dock = DockStyle.Fill;
            this._detailModeLabel.Text = "Detail mode:";
            this._detailModeLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._detailModeComboBox.Dock = DockStyle.Fill;
            this._detailModeComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            this._detailModeComboBox.Items.AddRange(new object[] { "compact", "balanced", "detailed" });
            this._detailModeComboBox.SelectedIndex = 1;
            this._logicModeLabel.Dock = DockStyle.Fill;
            this._logicModeLabel.Text = "Logic mode:";
            this._logicModeLabel.TextAlign = ContentAlignment.MiddleLeft;
            this._logicModeComboBox.Dock = DockStyle.Fill;
            this._logicModeComboBox.DropDownStyle = ComboBoxStyle.DropDownList;
            this._logicModeComboBox.Items.AddRange(new object[] { "data-only", "data-plus-script-plan", "no-scripts" });
            this._logicModeComboBox.SelectedIndex = 0;
            // 
            // _buttonLayout
            // 
            this._buttonLayout.ColumnCount = 8;
            this._buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120F));
            this._buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 190F));
            this._buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 210F));
            this._buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145F));
            this._buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
            this._buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 140F));
            this._buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
            this._buttonLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this._buttonLayout.Controls.Add(this._testLmStudioButton, 0, 0);
            this._buttonLayout.Controls.Add(this._aiHelperButton, 1, 0);
            this._buttonLayout.Controls.Add(this._generateButton, 2, 0);
            this._buttonLayout.Controls.Add(this._applyButton, 3, 0);
            this._buttonLayout.Controls.Add(this._saveButton, 4, 0);
            this._buttonLayout.Controls.Add(this._validateButton, 5, 0);
            this._buttonLayout.Controls.Add(this._cancelButton, 6, 0);
            this._buttonLayout.Controls.Add(this._statusLabel, 7, 0);
            this._buttonLayout.Dock = DockStyle.Fill;
            this._buttonLayout.TabIndex = 2;
            this._testLmStudioButton.Dock = DockStyle.Fill;
            this._testLmStudioButton.Text = "Тест LM Studio";
            this._testLmStudioButton.UseVisualStyleBackColor = true;
            this._aiHelperButton.Dock = DockStyle.Fill;
            this._aiHelperButton.Text = "ИИ: вопросы и варианты";
            this._aiHelperButton.UseVisualStyleBackColor = true;
            this._generateButton.Dock = DockStyle.Fill;
            this._generateButton.Text = "Сгенерировать playable slice";
            this._generateButton.UseVisualStyleBackColor = true;
            this._applyButton.Dock = DockStyle.Fill;
            this._applyButton.Enabled = false;
            this._applyButton.Text = "Применить";
            this._applyButton.UseVisualStyleBackColor = true;
            this._saveButton.Dock = DockStyle.Fill;
            this._saveButton.Text = "Сохранить";
            this._saveButton.UseVisualStyleBackColor = true;
            this._validateButton.Dock = DockStyle.Fill;
            this._validateButton.Text = "Проверить";
            this._validateButton.UseVisualStyleBackColor = true;
            this._cancelButton.Dock = DockStyle.Fill;
            this._cancelButton.Enabled = false;
            this._cancelButton.Text = "Отменить";
            this._cancelButton.UseVisualStyleBackColor = true;
            this._statusLabel.AutoEllipsis = true;
            this._statusLabel.Dock = DockStyle.Fill;
            this._statusLabel.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // _outputSplitContainer
            // 
            this._outputSplitContainer.Dock = DockStyle.Fill;
            this._outputSplitContainer.Location = new Point(11, 379);
            this._outputSplitContainer.Name = "_outputSplitContainer";
            this._outputSplitContainer.Panel1.Controls.Add(this._rawJsonTextBox);
            this._outputSplitContainer.Panel2.Controls.Add(this._resultTextBox);
            this._outputSplitContainer.Size = new Size(1078, 370);
            this._outputSplitContainer.SplitterDistance = 539;
            this._outputSplitContainer.TabIndex = 3;
            this._rawJsonTextBox.Dock = DockStyle.Fill;
            this._rawJsonTextBox.Font = new Font("Consolas", 9F, FontStyle.Regular, GraphicsUnit.Point);
            this._rawJsonTextBox.Multiline = true;
            this._rawJsonTextBox.ReadOnly = true;
            this._rawJsonTextBox.ScrollBars = ScrollBars.Both;
            this._rawJsonTextBox.WordWrap = false;
            this._resultTextBox.Dock = DockStyle.Fill;
            this._resultTextBox.Font = new Font("Consolas", 9F, FontStyle.Regular, GraphicsUnit.Point);
            this._resultTextBox.Multiline = true;
            this._resultTextBox.ReadOnly = true;
            this._resultTextBox.ScrollBars = ScrollBars.Both;
            this._resultTextBox.WordWrap = false;
            // 
            // GenerationPageControl
            // 
            this.AutoScaleDimensions = new SizeF(7F, 15F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.Controls.Add(this._rootLayout);
            this.Name = "GenerationPageControl";
            this.Size = new Size(1100, 760);
            this._rootLayout.ResumeLayout(false);
            this._topLayout.ResumeLayout(false);
            this._briefTabs.ResumeLayout(false);
            this._coreTabPage.ResumeLayout(false);
            this._advancedTabPage.ResumeLayout(false);
            this._scopeTabPage.ResumeLayout(false);
            this._coreLayout.ResumeLayout(false);
            this._coreLayout.PerformLayout();
            this._advancedLayout.ResumeLayout(false);
            this._advancedLayout.PerformLayout();
            this._scopeLayout.ResumeLayout(false);
            this._mapSizePanel.ResumeLayout(false);
            this._mapSizePanel.PerformLayout();
            ((ISupportInitialize)(this._mapWidthNumeric)).EndInit();
            ((ISupportInitialize)(this._mapHeightNumeric)).EndInit();
            ((ISupportInitialize)(this._maxTileOverridesNumeric)).EndInit();
            ((ISupportInitialize)(this._targetNpcNumeric)).EndInit();
            ((ISupportInitialize)(this._targetEntityNumeric)).EndInit();
            ((ISupportInitialize)(this._targetQuestNumeric)).EndInit();
            ((ISupportInitialize)(this._targetDialogueNumeric)).EndInit();
            this._buttonLayout.ResumeLayout(false);
            this._outputSplitContainer.Panel1.ResumeLayout(false);
            this._outputSplitContainer.Panel1.PerformLayout();
            this._outputSplitContainer.Panel2.ResumeLayout(false);
            this._outputSplitContainer.Panel2.PerformLayout();
            ((ISupportInitialize)(this._outputSplitContainer)).EndInit();
            this._outputSplitContainer.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
