using LLMGameCreator.Application.Design.ProjectStandaloneBuild;
using Xunit;

namespace LLMGameCreator.Tests.Application.Goal161S;

public sealed class Goal161SPointerPublicationTests
{
    [Fact] public void Behavioral_pointer_has_no_absolute_paths() { using var root = new Goal161STempRoot(); var location = root.Resolve("a1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, location); var pointer = Goal161STempRoot.Pointer(location); var publication = root.Locations.PublishCurrentPointer(location, pointer); var json = File.ReadAllText(location.CurrentPointerPath); Assert.True(publication.Passed, publication.Diagnostic); Assert.DoesNotContain(root.Path, json, StringComparison.OrdinalIgnoreCase); }
    [Fact] public void Behavioral_pointer_resolves_exact_confined_run() { using var root = new Goal161STempRoot(); var location = root.Resolve("a1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, location); Assert.True(root.Locations.PublishCurrentPointer(location, Goal161STempRoot.Pointer(location)).Passed); var read = root.Locations.LoadCurrentOutput(root.Project, "package"); Assert.True(read.Passed, read.Diagnostic); Assert.Equal(location.RunOutputFolder, read.RunOutputFolder); }
    [Fact] public void Behavioral_pointer_rejects_unsafe_run_name() { using var root = new Goal161STempRoot(); var location = root.Resolve("a1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, location); var result = root.Locations.PublishCurrentPointer(location, Goal161STempRoot.Pointer(location) with { RunDirectoryName = "r-../unsafe000" }); Assert.False(result.Passed); Assert.False(File.Exists(location.CurrentPointerPath)); }
    [Fact] public void Behavioral_atomic_pointer_write_creates_current() { using var root = new Goal161STempRoot(); var location = root.Resolve("a1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, location); var result = root.Locations.PublishCurrentPointer(location, Goal161STempRoot.Pointer(location)); Assert.True(result.Passed, result.Diagnostic); Assert.True(File.Exists(location.CurrentPointerPath)); Assert.NotEmpty(result.CurrentPointerSha256); }
    [Fact] public void Behavioral_atomic_pointer_replacement_changes_current_after_validation() { using var root = new Goal161STempRoot(); var one = root.Resolve("a1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, one); Assert.True(root.Locations.PublishCurrentPointer(one, Goal161STempRoot.Pointer(one)).Passed); var two = root.Resolve("b1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, two); var result = root.Locations.PublishCurrentPointer(two, Goal161STempRoot.Pointer(two)); Assert.True(result.Passed, result.Diagnostic); Assert.Equal(two.RunDirectoryName, root.Locations.LoadCurrentOutput(root.Project, "package").Pointer!.RunDirectoryName); }
    [Fact] public void Behavioral_restrictive_exe_handle_does_not_block_publication() { using var root = new Goal161STempRoot(); var location = root.Resolve("a1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, location); using var handle = new FileStream(Path.Combine(location.RunOutputFolder, "g.exe"), FileMode.Open, FileAccess.Read, FileShare.Read); var result = root.Locations.PublishCurrentPointer(location, Goal161STempRoot.Pointer(location)); Assert.True(result.Passed, result.Diagnostic); Assert.True(File.Exists(Path.Combine(location.RunOutputFolder, "g.exe"))); }
    [Fact] public void Behavioral_green_run_is_not_moved_by_publication() { using var root = new Goal161STempRoot(); var location = root.Resolve("a1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, location); var before = File.ReadAllBytes(Path.Combine(location.RunOutputFolder, "g.exe")); Assert.True(root.Locations.PublishCurrentPointer(location, Goal161STempRoot.Pointer(location)).Passed); Assert.Equal(before, File.ReadAllBytes(Path.Combine(location.RunOutputFolder, "g.exe"))); Assert.True(Directory.Exists(location.RunOutputFolder)); }
    [Fact] public void Behavioral_pointer_hashes_do_not_require_operational_absolute_path() { using var root = new Goal161STempRoot(); var location = root.Resolve("a1b2c3d4e5f6"); Goal161STempRoot.WriteGreenRun(root.Locations, location); var result = root.Locations.PublishCurrentPointer(location, Goal161STempRoot.Pointer(location)); Assert.True(result.Passed); Assert.True(root.Locations.LoadCurrentOutput(root.Project, "package").Passed); }
}
